// ============================================================
// OFFENSE - MELEE ABILITIES
// Blade mastery, close combat, impact techniques
// ============================================================

import { ExportedAbility } from '../types';

export const MELEE_ABILITIES: Record<string, ExportedAbility> = {
  'blade-mastery-protocol': {
    id: 301,
    slug: 'blade-mastery-protocol',
    name: 'Blade Mastery Protocol',
    description: 'Neural-enhanced edged weapon proficiency that optimizes cutting angles and strike timing.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: 'Passive', cooldown: '-', effectDescription: '+10% melee damage with bladed weapons.' },
      { level: 2, duration: 'Passive', cooldown: '-', effectDescription: '+15% melee damage; improved attack speed.' },
      { level: 3, duration: 'Passive', cooldown: '-', effectDescription: '+20% melee damage; +5% critical chance.' },
      { level: 4, duration: 'Passive', cooldown: '-', effectDescription: '+25% melee damage; bleeding wounds.' },
      { level: 5, duration: 'Passive', cooldown: '-', effectDescription: '+30% melee damage; +10% critical chance.' },
      { level: 6, duration: 'Passive', cooldown: '-', effectDescription: '+35% melee damage; armor penetration +10%.' },
      { level: 7, duration: 'Passive', cooldown: '-', effectDescription: '+40% melee damage; +15% critical chance.' },
      { level: 8, duration: 'Passive', cooldown: '-', effectDescription: '+45% melee damage; deep wounds cause slow.' },
      { level: 9, duration: 'Passive', cooldown: '-', effectDescription: '+50% melee damage; +20% critical chance.' },
      { level: 10, duration: 'Passive', cooldown: '-', effectDescription: 'Blade Master: +75% melee damage; +30% crit; can cut through armored targets.' },
    ],
  },
  'blade-convergence': {
    id: 302,
    slug: 'blade-convergence',
    name: 'Blade Convergence',
    description: 'Multi-strike technique that focuses repeated attacks on a single point for devastating penetration.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '3 sec', cooldown: '45 sec', effectDescription: '2 rapid strikes on same point; +20% penetration.' },
      { level: 2, duration: '3.5 sec', cooldown: '42 sec', effectDescription: '3 strikes; +25% penetration.' },
      { level: 3, duration: '4 sec', cooldown: '39 sec', effectDescription: '3 strikes; +30% penetration; stagger on hit.' },
      { level: 4, duration: '4.5 sec', cooldown: '36 sec', effectDescription: '4 strikes; +35% penetration.' },
      { level: 5, duration: '5 sec', cooldown: '33 sec', effectDescription: '4 strikes; +40% penetration; armor break.' },
      { level: 6, duration: '5.5 sec', cooldown: '30 sec', effectDescription: '5 strikes; +45% penetration.' },
      { level: 7, duration: '6 sec', cooldown: '27 sec', effectDescription: '5 strikes; +50% penetration; pierces shields.' },
      { level: 8, duration: '6.5 sec', cooldown: '24 sec', effectDescription: '6 strikes; +60% penetration.' },
      { level: 9, duration: '7 sec', cooldown: '21 sec', effectDescription: '6 strikes; +70% penetration; guaranteed crit.' },
      { level: 10, duration: '8 sec', cooldown: '18 sec', effectDescription: 'Perfect Convergence: 8 strikes; 100% penetration; ignores all armor.' },
    ],
  },
  'lethal-interval-mode': {
    id: 303,
    slug: 'lethal-interval-mode',
    name: 'Lethal Interval Mode',
    description: 'Combat state that identifies and exploits micro-gaps in enemy defense timing.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '10 sec', cooldown: '60 sec', effectDescription: 'Highlight enemy defense gaps; +15% hit chance.' },
      { level: 2, duration: '12 sec', cooldown: '55 sec', effectDescription: 'Gaps easier to exploit; +20% hit chance.' },
      { level: 3, duration: '14 sec', cooldown: '50 sec', effectDescription: 'Auto-adjust strike timing; +25% hit chance.' },
      { level: 4, duration: '16 sec', cooldown: '45 sec', effectDescription: 'Damage bonus on gap hits +20%; +30% hit.' },
      { level: 5, duration: '18 sec', cooldown: '40 sec', effectDescription: 'See gaps in guard animations; +35% hit.' },
      { level: 6, duration: '20 sec', cooldown: '35 sec', effectDescription: 'Gap hits cause stagger; +40% hit chance.' },
      { level: 7, duration: '22 sec', cooldown: '30 sec', effectDescription: 'Faster gap exploitation; +45% hit chance.' },
      { level: 8, duration: '25 sec', cooldown: '27 sec', effectDescription: 'Gap hits deal +50% damage; +50% hit.' },
      { level: 9, duration: '28 sec', cooldown: '24 sec', effectDescription: 'Create gaps in enemy defense; +55% hit.' },
      { level: 10, duration: '35 sec', cooldown: '20 sec', effectDescription: 'Predator Mode: Always find the gap; +100% damage on gap hits.' },
    ],
  },
  'tomahawk-trajectory': {
    id: 304,
    slug: 'tomahawk-trajectory',
    name: 'Tomahawk Trajectory',
    description: 'Throwing weapon expertise that calculates optimal spin, arc, and impact angle.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: 'Passive', cooldown: '30 sec', effectDescription: 'Thrown melee +15% accuracy and damage.' },
      { level: 2, duration: 'Passive', cooldown: '28 sec', effectDescription: '+20% accuracy and damage; spin stabilized.' },
      { level: 3, duration: 'Passive', cooldown: '26 sec', effectDescription: '+25% accuracy and damage; ricochet chance.' },
      { level: 4, duration: 'Passive', cooldown: '24 sec', effectDescription: '+30% accuracy and damage; range +20%.' },
      { level: 5, duration: 'Passive', cooldown: '22 sec', effectDescription: '+35% accuracy and damage; can recall thrown.' },
      { level: 6, duration: 'Passive', cooldown: '20 sec', effectDescription: '+40% accuracy; multi-target ricochet.' },
      { level: 7, duration: 'Passive', cooldown: '18 sec', effectDescription: '+45% damage; pierce through targets.' },
      { level: 8, duration: 'Passive', cooldown: '16 sec', effectDescription: '+50% damage; curve around obstacles.' },
      { level: 9, duration: 'Passive', cooldown: '14 sec', effectDescription: '+60% damage; instant recall; no cooldown.' },
      { level: 10, duration: 'Passive', cooldown: '10 sec', effectDescription: 'Tomahawk Master: +100% damage; throws never miss; infinite ricochet.' },
    ],
  },
  'harmonic-impact-dampener': {
    id: 305,
    slug: 'harmonic-impact-dampener',
    name: 'Harmonic Impact Dampener',
    description: 'TL9 vibration technology that amplifies strike force while reducing strain on user.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '15 sec', cooldown: '90 sec', effectDescription: 'Melee strikes deal +10% damage; recoil reduced.' },
      { level: 2, duration: '18 sec', cooldown: '85 sec', effectDescription: '+15% damage; stamina cost reduced 10%.' },
      { level: 3, duration: '21 sec', cooldown: '80 sec', effectDescription: '+20% damage; attacks cause minor stagger.' },
      { level: 4, duration: '24 sec', cooldown: '75 sec', effectDescription: '+25% damage; stamina cost reduced 20%.' },
      { level: 5, duration: '27 sec', cooldown: '70 sec', effectDescription: '+30% damage; attacks cause internal damage.' },
      { level: 6, duration: '30 sec', cooldown: '65 sec', effectDescription: '+35% damage; ignore partial armor.' },
      { level: 7, duration: '35 sec', cooldown: '60 sec', effectDescription: '+40% damage; attacks cause severe stagger.' },
      { level: 8, duration: '40 sec', cooldown: '55 sec', effectDescription: '+45% damage; stamina cost reduced 40%.' },
      { level: 9, duration: '45 sec', cooldown: '50 sec', effectDescription: '+50% damage; shatter bones on crit.' },
      { level: 10, duration: '60 sec', cooldown: '40 sec', effectDescription: 'Resonance Destruction: +100% damage; attacks ignore all armor; no stamina cost.' },
    ],
  },
};
