// ============================================================
// OFFENSE - RANGED ABILITIES
// Firearm handling, accuracy, weapon mechanics, shooting techniques
// ============================================================

import { ExportedAbility } from '../types';

export const RANGED_ABILITIES: Record<string, ExportedAbility> = {
  'firearm-handling': {
    id: 311,
    slug: 'firearm-handling',
    name: 'Firearm Handling',
    description: 'Neural-enhanced weapon proficiency that improves accuracy, recoil control, and reload speed.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: 'Passive', cooldown: '-', effectDescription: '+10% accuracy; -5% recoil.' },
      { level: 2, duration: 'Passive', cooldown: '-', effectDescription: '+15% accuracy; -10% recoil.' },
      { level: 3, duration: 'Passive', cooldown: '-', effectDescription: '+20% accuracy; -15% recoil; faster ADS.' },
      { level: 4, duration: 'Passive', cooldown: '-', effectDescription: '+25% accuracy; -20% recoil.' },
      { level: 5, duration: 'Passive', cooldown: '-', effectDescription: '+30% accuracy; -25% recoil; +10% reload speed.' },
      { level: 6, duration: 'Passive', cooldown: '-', effectDescription: '+35% accuracy; -30% recoil.' },
      { level: 7, duration: 'Passive', cooldown: '-', effectDescription: '+40% accuracy; -35% recoil; +20% reload.' },
      { level: 8, duration: 'Passive', cooldown: '-', effectDescription: '+45% accuracy; -40% recoil.' },
      { level: 9, duration: 'Passive', cooldown: '-', effectDescription: '+50% accuracy; -50% recoil; +30% reload.' },
      { level: 10, duration: 'Passive', cooldown: '-', effectDescription: 'Weapon Master: +75% accuracy; near-zero recoil; instant reload.' },
    ],
  },
  'reflex-shot': {
    id: 312,
    slug: 'reflex-shot',
    name: 'Reflex Shot',
    description: 'Neural-accelerated snap-shooting that enables lightning-fast target acquisition.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '8 sec', cooldown: '45 sec', effectDescription: 'First shot +30% accuracy; ADS speed +20%.' },
      { level: 2, duration: '10 sec', cooldown: '42 sec', effectDescription: 'First shot +40% accuracy; ADS speed +25%.' },
      { level: 3, duration: '12 sec', cooldown: '39 sec', effectDescription: 'First 2 shots +45% accuracy; ADS +30%.' },
      { level: 4, duration: '14 sec', cooldown: '36 sec', effectDescription: 'First 2 shots +50% accuracy; ADS +35%.' },
      { level: 5, duration: '16 sec', cooldown: '33 sec', effectDescription: 'First 3 shots +55% accuracy; ADS +40%.' },
      { level: 6, duration: '18 sec', cooldown: '30 sec', effectDescription: 'First 3 shots +60% accuracy; ADS +50%.' },
      { level: 7, duration: '20 sec', cooldown: '27 sec', effectDescription: 'First 4 shots +65% accuracy; instant ADS.' },
      { level: 8, duration: '22 sec', cooldown: '24 sec', effectDescription: 'First 4 shots +70% accuracy; auto-aim assist.' },
      { level: 9, duration: '25 sec', cooldown: '21 sec', effectDescription: 'First 5 shots +80% accuracy; perfect ADS.' },
      { level: 10, duration: '30 sec', cooldown: '18 sec', effectDescription: 'Lightning Draw: All shots +100% accuracy; instant target lock.' },
    ],
  },
  'quickdraw-matrix': {
    id: 313,
    slug: 'quickdraw-matrix',
    name: 'Quickdraw Matrix',
    description: 'Pre-calculated draw sequences that minimize weapon deployment time.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: 'Passive', cooldown: '-', effectDescription: 'Weapon swap speed +20%.' },
      { level: 2, duration: 'Passive', cooldown: '-', effectDescription: 'Weapon swap speed +30%; holster during sprint.' },
      { level: 3, duration: 'Passive', cooldown: '-', effectDescription: 'Weapon swap speed +40%.' },
      { level: 4, duration: 'Passive', cooldown: '-', effectDescription: 'Swap speed +50%; can fire mid-swap.' },
      { level: 5, duration: 'Passive', cooldown: '-', effectDescription: 'Swap speed +60%; swap doesn\'t interrupt aim.' },
      { level: 6, duration: 'Passive', cooldown: '-', effectDescription: 'Swap speed +70%; dual-wield swap.' },
      { level: 7, duration: 'Passive', cooldown: '-', effectDescription: 'Near-instant swap speed.' },
      { level: 8, duration: 'Passive', cooldown: '-', effectDescription: 'Swap preserves aim on target.' },
      { level: 9, duration: 'Passive', cooldown: '-', effectDescription: 'First shot after swap +50% damage.' },
      { level: 10, duration: 'Passive', cooldown: '-', effectDescription: 'Gunslinger: Instant weapon swap; +100% damage on first shot.' },
    ],
  },
  'recoil-null-pattern': {
    id: 314,
    slug: 'recoil-null-pattern',
    name: 'Recoil Null Pattern',
    description: 'Predictive micro-adjustment system that counters weapon recoil in real-time.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '15 sec', cooldown: '60 sec', effectDescription: 'Reduce recoil by 25%.' },
      { level: 2, duration: '18 sec', cooldown: '55 sec', effectDescription: 'Reduce recoil by 35%.' },
      { level: 3, duration: '21 sec', cooldown: '50 sec', effectDescription: 'Reduce recoil by 45%; pattern stabilized.' },
      { level: 4, duration: '24 sec', cooldown: '45 sec', effectDescription: 'Reduce recoil by 55%.' },
      { level: 5, duration: '27 sec', cooldown: '40 sec', effectDescription: 'Reduce recoil by 65%; full-auto viable.' },
      { level: 6, duration: '30 sec', cooldown: '35 sec', effectDescription: 'Reduce recoil by 75%.' },
      { level: 7, duration: '35 sec', cooldown: '30 sec', effectDescription: 'Reduce recoil by 85%; near-zero muzzle rise.' },
      { level: 8, duration: '40 sec', cooldown: '27 sec', effectDescription: 'Reduce recoil by 90%.' },
      { level: 9, duration: '45 sec', cooldown: '24 sec', effectDescription: 'Reduce recoil by 95%; pinpoint accuracy.' },
      { level: 10, duration: '60 sec', cooldown: '20 sec', effectDescription: 'Recoil Elimination: Zero recoil; full-auto sniper accuracy.' },
    ],
  },
  'impact-angle-assist': {
    id: 315,
    slug: 'impact-angle-assist',
    name: 'Impact Angle Assist',
    description: 'Ballistic calculation system that optimizes projectile angle for maximum damage.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '10 sec', cooldown: '45 sec', effectDescription: '+10% damage on optimal angle shots.' },
      { level: 2, duration: '12 sec', cooldown: '42 sec', effectDescription: '+15% damage; shows optimal angle on HUD.' },
      { level: 3, duration: '14 sec', cooldown: '39 sec', effectDescription: '+20% damage; auto-adjusts aim slightly.' },
      { level: 4, duration: '16 sec', cooldown: '36 sec', effectDescription: '+25% damage; armor weak points highlighted.' },
      { level: 5, duration: '18 sec', cooldown: '33 sec', effectDescription: '+30% damage; penetration improved.' },
      { level: 6, duration: '20 sec', cooldown: '30 sec', effectDescription: '+35% damage; ricochet calculation.' },
      { level: 7, duration: '22 sec', cooldown: '27 sec', effectDescription: '+40% damage; bypass partial cover.' },
      { level: 8, duration: '25 sec', cooldown: '24 sec', effectDescription: '+45% damage; guaranteed penetration.' },
      { level: 9, duration: '28 sec', cooldown: '21 sec', effectDescription: '+50% damage; shots deflect into targets.' },
      { level: 10, duration: '35 sec', cooldown: '18 sec', effectDescription: 'Perfect Impact: +75% damage; all shots hit optimal angle.' },
    ],
  },
  'micro-dampener-lattice': {
    id: 316,
    slug: 'micro-dampener-lattice',
    name: 'Micro-Dampener Lattice',
    description: 'Energy absorption grid that reduces weapon heat and firing strain.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '20 sec', cooldown: '60 sec', effectDescription: 'Weapon heat buildup -20%.' },
      { level: 2, duration: '25 sec', cooldown: '55 sec', effectDescription: 'Heat buildup -30%; overheat threshold +10%.' },
      { level: 3, duration: '30 sec', cooldown: '50 sec', effectDescription: 'Heat buildup -40%.' },
      { level: 4, duration: '35 sec', cooldown: '45 sec', effectDescription: 'Heat buildup -50%; faster heat dissipation.' },
      { level: 5, duration: '40 sec', cooldown: '40 sec', effectDescription: 'Heat buildup -60%.' },
      { level: 6, duration: '45 sec', cooldown: '35 sec', effectDescription: 'Heat buildup -70%; overheat threshold +25%.' },
      { level: 7, duration: '50 sec', cooldown: '30 sec', effectDescription: 'Heat buildup -80%.' },
      { level: 8, duration: '55 sec', cooldown: '27 sec', effectDescription: 'Heat buildup -90%; no jam chance.' },
      { level: 9, duration: '60 sec', cooldown: '24 sec', effectDescription: 'Near-zero heat buildup.' },
      { level: 10, duration: '90 sec', cooldown: '20 sec', effectDescription: 'Cold Fire: No heat buildup; infinite sustained fire.' },
    ],
  },
  'overheat-channel-mode': {
    id: 317,
    slug: 'overheat-channel-mode',
    name: 'Overheat Channel Mode',
    description: 'Converts weapon heat into bonus damage instead of malfunction.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '10 sec', cooldown: '90 sec', effectDescription: 'Heat converts to +10% damage instead of jam.' },
      { level: 2, duration: '12 sec', cooldown: '85 sec', effectDescription: 'Heat converts to +15% damage.' },
      { level: 3, duration: '14 sec', cooldown: '80 sec', effectDescription: 'Heat converts to +20% damage; fire damage added.' },
      { level: 4, duration: '16 sec', cooldown: '75 sec', effectDescription: 'Heat converts to +25% damage.' },
      { level: 5, duration: '18 sec', cooldown: '70 sec', effectDescription: 'Heat converts to +30% damage; ignite targets.' },
      { level: 6, duration: '20 sec', cooldown: '65 sec', effectDescription: 'Heat converts to +40% damage.' },
      { level: 7, duration: '22 sec', cooldown: '60 sec', effectDescription: 'Heat converts to +50% damage; melt armor.' },
      { level: 8, duration: '25 sec', cooldown: '55 sec', effectDescription: 'Heat converts to +60% damage.' },
      { level: 9, duration: '28 sec', cooldown: '50 sec', effectDescription: 'Heat converts to +75% damage; plasma rounds.' },
      { level: 10, duration: '35 sec', cooldown: '40 sec', effectDescription: 'Volcanic Fury: Heat becomes +150% damage; weapon cannot overheat.' },
    ],
  },
};
