// ============================================================
// DEFENSE & MITIGATION ABILITIES
// Shields, dampening, armor, stabilization, stress reduction
// ============================================================

import { ExportedAbility } from './types';

export const DEFENSE_MITIGATION_ABILITIES: Record<string, ExportedAbility> = {
  'guard-vector-assist': {
    id: 401,
    slug: 'guard-vector-assist',
    name: 'Guard Vector Assist',
    description: 'Predictive defense system that calculates optimal blocking angles in real-time.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '12 sec', cooldown: '45 sec', effectDescription: 'Block efficiency +15%; shows attack vectors.' },
      { level: 2, duration: '14 sec', cooldown: '42 sec', effectDescription: 'Block efficiency +20%; auto-angle shield.' },
      { level: 3, duration: '16 sec', cooldown: '39 sec', effectDescription: 'Block efficiency +25%; partial auto-block.' },
      { level: 4, duration: '18 sec', cooldown: '36 sec', effectDescription: 'Block efficiency +30%; stamina cost reduced.' },
      { level: 5, duration: '20 sec', cooldown: '33 sec', effectDescription: 'Block efficiency +40%; perfect parry window +50%.' },
      { level: 6, duration: '22 sec', cooldown: '30 sec', effectDescription: 'Block efficiency +50%; riposte opportunities.' },
      { level: 7, duration: '25 sec', cooldown: '27 sec', effectDescription: 'Block efficiency +60%; auto-parry light attacks.' },
      { level: 8, duration: '28 sec', cooldown: '24 sec', effectDescription: 'Block efficiency +70%; reflect projectiles.' },
      { level: 9, duration: '32 sec', cooldown: '21 sec', effectDescription: 'Block efficiency +80%; stagger attackers.' },
      { level: 10, duration: '40 sec', cooldown: '18 sec', effectDescription: 'Perfect Guard: 100% block efficiency; auto-counter all attacks.' },
    ],
  },
  'kinetic-diffusion-shell': {
    id: 402,
    slug: 'kinetic-diffusion-shell',
    name: 'Kinetic Diffusion Shell',
    description: 'Energy barrier that distributes impact force across the body, reducing localized damage.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '15 sec', cooldown: '60 sec', effectDescription: 'Distribute 20% of impact damage.' },
      { level: 2, duration: '18 sec', cooldown: '55 sec', effectDescription: 'Distribute 30% of impact; reduces stagger.' },
      { level: 3, duration: '21 sec', cooldown: '50 sec', effectDescription: 'Distribute 40% of impact.' },
      { level: 4, duration: '24 sec', cooldown: '45 sec', effectDescription: 'Distribute 50% of impact; immune to knockback.' },
      { level: 5, duration: '27 sec', cooldown: '40 sec', effectDescription: 'Distribute 60% of impact.' },
      { level: 6, duration: '30 sec', cooldown: '35 sec', effectDescription: 'Distribute 70% of impact; absorb explosions.' },
      { level: 7, duration: '35 sec', cooldown: '30 sec', effectDescription: 'Distribute 80% of impact.' },
      { level: 8, duration: '40 sec', cooldown: '27 sec', effectDescription: 'Distribute 90% of impact; share with ally.' },
      { level: 9, duration: '45 sec', cooldown: '24 sec', effectDescription: 'Distribute 95% of impact; heal from absorbed.' },
      { level: 10, duration: '60 sec', cooldown: '20 sec', effectDescription: 'Kinetic Immunity: 100% diffusion; impacts heal instead of damage.' },
    ],
  },
  'shock-mitigation-pulse': {
    id: 403,
    slug: 'shock-mitigation-pulse',
    name: 'Shock Mitigation Pulse',
    description: 'Emergency system that absorbs sudden damage spikes and converts them to manageable DoT.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: 'Reactive', cooldown: '90 sec', effectDescription: 'Absorb 30% of damage over 100; convert to 5sec DoT.' },
      { level: 2, duration: 'Reactive', cooldown: '85 sec', effectDescription: 'Absorb 40% of spike damage.' },
      { level: 3, duration: 'Reactive', cooldown: '80 sec', effectDescription: 'Absorb 50% of spike damage; reduce DoT.' },
      { level: 4, duration: 'Reactive', cooldown: '75 sec', effectDescription: 'Absorb 60% of spike damage.' },
      { level: 5, duration: 'Reactive', cooldown: '70 sec', effectDescription: 'Absorb 70% of spike; heal during DoT.' },
      { level: 6, duration: 'Reactive', cooldown: '65 sec', effectDescription: 'Absorb 80% of spike damage.' },
      { level: 7, duration: 'Reactive', cooldown: '60 sec', effectDescription: 'Absorb 85% of spike; minimal DoT.' },
      { level: 8, duration: 'Reactive', cooldown: '55 sec', effectDescription: 'Absorb 90% of spike damage.' },
      { level: 9, duration: 'Reactive', cooldown: '50 sec', effectDescription: 'Absorb 95% of spike; no DoT.' },
      { level: 10, duration: 'Reactive', cooldown: '40 sec', effectDescription: 'Damage Cap: No single hit can exceed 10% max HP.' },
    ],
  },
  'pain-response-dampener': {
    id: 404,
    slug: 'pain-response-dampener',
    name: 'Pain Response Dampener',
    description: 'Neural interface that suppresses pain signals, allowing continued combat while injured.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '20 sec', cooldown: '90 sec', effectDescription: 'Ignore 10% of received damage effects.' },
      { level: 2, duration: '25 sec', cooldown: '85 sec', effectDescription: 'Ignore 15% of damage effects; no flinch.' },
      { level: 3, duration: '30 sec', cooldown: '80 sec', effectDescription: 'Ignore 20% of damage effects.' },
      { level: 4, duration: '35 sec', cooldown: '75 sec', effectDescription: 'Ignore 25% of damage effects; immune to stun.' },
      { level: 5, duration: '40 sec', cooldown: '70 sec', effectDescription: 'Ignore 30% of damage effects.' },
      { level: 6, duration: '45 sec', cooldown: '65 sec', effectDescription: 'Ignore 40% of damage effects; move at full speed.' },
      { level: 7, duration: '50 sec', cooldown: '60 sec', effectDescription: 'Ignore 50% of damage effects.' },
      { level: 8, duration: '55 sec', cooldown: '55 sec', effectDescription: 'Ignore 60% of damage effects; adrenaline boost.' },
      { level: 9, duration: '60 sec', cooldown: '50 sec', effectDescription: 'Ignore 75% of damage effects.' },
      { level: 10, duration: '90 sec', cooldown: '40 sec', effectDescription: 'Pain Immunity: Ignore all damage effects; fight at 1 HP.' },
    ],
  },
  'adrenal-auto-regulation-boost': {
    id: 405,
    slug: 'adrenal-auto-regulation-boost',
    name: 'Adrenal Auto-Regulation Boost',
    description: 'Bio-chemical injector that releases combat stimulants when health drops critically.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '10 sec', cooldown: '120 sec', effectDescription: 'At <30% HP: +10% damage, +10% speed.' },
      { level: 2, duration: '12 sec', cooldown: '110 sec', effectDescription: 'Trigger at <35% HP; +15% damage/speed.' },
      { level: 3, duration: '14 sec', cooldown: '100 sec', effectDescription: 'Trigger at <40% HP; +20% damage/speed.' },
      { level: 4, duration: '16 sec', cooldown: '90 sec', effectDescription: '+25% damage/speed; pain suppression.' },
      { level: 5, duration: '18 sec', cooldown: '80 sec', effectDescription: '+30% damage/speed; heal 5% HP.' },
      { level: 6, duration: '20 sec', cooldown: '70 sec', effectDescription: '+40% damage/speed.' },
      { level: 7, duration: '22 sec', cooldown: '60 sec', effectDescription: '+50% damage/speed; brief invulnerability.' },
      { level: 8, duration: '25 sec', cooldown: '55 sec', effectDescription: '+60% damage/speed; heal 10% HP.' },
      { level: 9, duration: '28 sec', cooldown: '50 sec', effectDescription: '+75% damage/speed.' },
      { level: 10, duration: '35 sec', cooldown: '40 sec', effectDescription: 'Berserker Mode: +100% damage/speed; cannot die during duration.' },
    ],
  },
  'bio-structural-integrity-mapping': {
    id: 406,
    slug: 'bio-structural-integrity-mapping',
    name: 'Bio-Structural Integrity Mapping',
    description: 'Medical scanner that monitors internal damage and optimizes regeneration priority.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '30 sec', cooldown: '90 sec', effectDescription: 'Regen +10%; prioritize critical organs.' },
      { level: 2, duration: '35 sec', cooldown: '85 sec', effectDescription: 'Regen +15%; detect internal bleeding.' },
      { level: 3, duration: '40 sec', cooldown: '80 sec', effectDescription: 'Regen +20%; auto-stabilize wounds.' },
      { level: 4, duration: '45 sec', cooldown: '75 sec', effectDescription: 'Regen +25%; prevent organ failure.' },
      { level: 5, duration: '50 sec', cooldown: '70 sec', effectDescription: 'Regen +30%; resist poisons.' },
      { level: 6, duration: '55 sec', cooldown: '65 sec', effectDescription: 'Regen +40%; regenerate limbs slowly.' },
      { level: 7, duration: '60 sec', cooldown: '60 sec', effectDescription: 'Regen +50%; immune to bleed.' },
      { level: 8, duration: '70 sec', cooldown: '55 sec', effectDescription: 'Regen +60%; share with ally.' },
      { level: 9, duration: '80 sec', cooldown: '50 sec', effectDescription: 'Regen +75%; rapid limb regrowth.' },
      { level: 10, duration: '120 sec', cooldown: '40 sec', effectDescription: 'Bio-Regeneration: +100% regen; regenerate from any non-lethal damage.' },
    ],
  },
  'defensive-shield-pulse': {
    id: 407,
    slug: 'defensive-shield-pulse',
    name: 'Defensive Shield Pulse',
    description: 'TL9 energy projection that creates a temporary protective barrier.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '6 sec', cooldown: '60 sec', effectDescription: 'Deploy shield absorbing 200 damage.' },
      { level: 2, duration: '7 sec', cooldown: '55 sec', effectDescription: 'Shield absorbs 300 damage.' },
      { level: 3, duration: '8 sec', cooldown: '50 sec', effectDescription: 'Shield absorbs 400 damage; blocks melee.' },
      { level: 4, duration: '9 sec', cooldown: '45 sec', effectDescription: 'Shield absorbs 500 damage.' },
      { level: 5, duration: '10 sec', cooldown: '40 sec', effectDescription: 'Shield absorbs 700 damage; reflects projectiles 20%.' },
      { level: 6, duration: '12 sec', cooldown: '35 sec', effectDescription: 'Shield absorbs 900 damage.' },
      { level: 7, duration: '14 sec', cooldown: '30 sec', effectDescription: 'Shield absorbs 1200 damage; blocks explosions.' },
      { level: 8, duration: '16 sec', cooldown: '27 sec', effectDescription: 'Shield absorbs 1500 damage.' },
      { level: 9, duration: '18 sec', cooldown: '24 sec', effectDescription: 'Shield absorbs 2000 damage; reflects 50%.' },
      { level: 10, duration: '25 sec', cooldown: '20 sec', effectDescription: 'Aegis Shield: Absorbs unlimited damage; full reflection.' },
    ],
  },
  'reactive-shield-pulse': {
    id: 408,
    slug: 'reactive-shield-pulse',
    name: 'Reactive Shield Pulse',
    description: 'TL9 intelligent barrier that activates automatically when attacks are detected.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: 'Reactive', cooldown: '45 sec', effectDescription: 'Auto-activate on incoming attack; block 50% damage.' },
      { level: 2, duration: 'Reactive', cooldown: '42 sec', effectDescription: 'Block 60% damage; faster activation.' },
      { level: 3, duration: 'Reactive', cooldown: '39 sec', effectDescription: 'Block 70% damage.' },
      { level: 4, duration: 'Reactive', cooldown: '36 sec', effectDescription: 'Block 75% damage; auto-aim block.' },
      { level: 5, duration: 'Reactive', cooldown: '33 sec', effectDescription: 'Block 80% damage.' },
      { level: 6, duration: 'Reactive', cooldown: '30 sec', effectDescription: 'Block 85% damage; stagger attacker.' },
      { level: 7, duration: 'Reactive', cooldown: '27 sec', effectDescription: 'Block 90% damage.' },
      { level: 8, duration: 'Reactive', cooldown: '24 sec', effectDescription: 'Block 95% damage; counter-pulse.' },
      { level: 9, duration: 'Reactive', cooldown: '21 sec', effectDescription: 'Block 100% damage.' },
      { level: 10, duration: 'Reactive', cooldown: '15 sec', effectDescription: 'Perfect Reaction: Auto-block all attacks; reflect damage to source.' },
    ],
  },
  'guardian-assault-protocol': {
    id: 409,
    slug: 'guardian-assault-protocol',
    name: 'Guardian Assault Protocol',
    description: 'TL9 defensive-offensive stance that converts blocked damage into counterattack power.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '15 sec', cooldown: '90 sec', effectDescription: 'Blocked damage becomes +10% counter damage.' },
      { level: 2, duration: '18 sec', cooldown: '85 sec', effectDescription: 'Blocked damage becomes +15% counter.' },
      { level: 3, duration: '21 sec', cooldown: '80 sec', effectDescription: 'Blocked damage becomes +20% counter; auto-counter.' },
      { level: 4, duration: '24 sec', cooldown: '75 sec', effectDescription: 'Blocked damage becomes +25% counter.' },
      { level: 5, duration: '27 sec', cooldown: '70 sec', effectDescription: 'Blocked damage becomes +35% counter; stagger attackers.' },
      { level: 6, duration: '30 sec', cooldown: '65 sec', effectDescription: 'Blocked damage becomes +45% counter.' },
      { level: 7, duration: '35 sec', cooldown: '60 sec', effectDescription: 'Blocked damage becomes +60% counter; chain counters.' },
      { level: 8, duration: '40 sec', cooldown: '55 sec', effectDescription: 'Blocked damage becomes +75% counter.' },
      { level: 9, duration: '45 sec', cooldown: '50 sec', effectDescription: 'Blocked damage becomes +100% counter.' },
      { level: 10, duration: '60 sec', cooldown: '40 sec', effectDescription: 'Retribution: Blocked damage returns as +200% counter; enemies fear to attack.' },
    ],
  },
};
