// ============================================================
// MOVEMENT & POSITIONING ABILITIES
// Mobility, micro-maneuvers, bracing, stability, repositioning
// ============================================================

import { ExportedAbility } from './types';

export const MOVEMENT_POSITIONING_ABILITIES: Record<string, ExportedAbility> = {
  'veil-step': {
    id: 101,
    slug: 'veil-step',
    name: 'Veil Step',
    description: 'Neural-accelerated movement protocol that creates brief optical distortion during rapid repositioning.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '1 sec', cooldown: '45 sec', effectDescription: 'Short burst of movement that blurs the user\'s silhouette; +10% evasion during step.' },
      { level: 2, duration: '1.2 sec', cooldown: '42 sec', effectDescription: 'Extended blur duration; +15% evasion during step.' },
      { level: 3, duration: '1.4 sec', cooldown: '39 sec', effectDescription: 'Leaves a faint afterimage that distracts enemies for 0.5 sec.' },
      { level: 4, duration: '1.6 sec', cooldown: '36 sec', effectDescription: 'Step distance increased by 25%; +20% evasion during step.' },
      { level: 5, duration: '1.8 sec', cooldown: '33 sec', effectDescription: 'Can phase through thin obstacles (doors, fences) during step.' },
      { level: 6, duration: '2 sec', cooldown: '30 sec', effectDescription: 'Afterimage now draws enemy fire for 1 sec; +25% evasion.' },
      { level: 7, duration: '2.2 sec', cooldown: '27 sec', effectDescription: 'Can chain two steps in quick succession.' },
      { level: 8, duration: '2.5 sec', cooldown: '24 sec', effectDescription: 'Step leaves no sound or thermal trace; +30% evasion.' },
      { level: 9, duration: '3 sec', cooldown: '20 sec', effectDescription: 'Can step through solid walls up to 1m thick.' },
      { level: 10, duration: '4 sec', cooldown: '15 sec', effectDescription: 'Shadow Phase: Near-teleportation speed; +50% evasion; enemies lose target lock completely.' },
    ],
  },
  'kinetic-drive-burst': {
    id: 102,
    slug: 'kinetic-drive-burst',
    name: 'Kinetic Drive Burst',
    description: 'Explosive acceleration module that converts stored energy into immediate forward velocity.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '2 sec', cooldown: '60 sec', effectDescription: 'Burst forward at 150% movement speed.' },
      { level: 2, duration: '2.5 sec', cooldown: '55 sec', effectDescription: 'Burst speed increased to 175%; minor knockback to enemies in path.' },
      { level: 3, duration: '3 sec', cooldown: '50 sec', effectDescription: 'Burst speed 200%; can knock down light enemies.' },
      { level: 4, duration: '3.5 sec', cooldown: '45 sec', effectDescription: 'Generates kinetic shield during burst (+15% damage reduction).' },
      { level: 5, duration: '4 sec', cooldown: '40 sec', effectDescription: 'Can change direction once mid-burst; speed 225%.' },
      { level: 6, duration: '4.5 sec', cooldown: '35 sec', effectDescription: 'Impact at end of burst deals damage equal to 50% of distance traveled.' },
      { level: 7, duration: '5 sec', cooldown: '30 sec', effectDescription: 'Can grab and carry one ally during burst; speed 250%.' },
      { level: 8, duration: '5.5 sec', cooldown: '25 sec', effectDescription: 'Sonic boom at burst start staggers nearby enemies.' },
      { level: 9, duration: '6 sec', cooldown: '22 sec', effectDescription: 'Can burst vertically (jumping/falling); speed 275%.' },
      { level: 10, duration: '8 sec', cooldown: '18 sec', effectDescription: 'Hypersonic Charge: 400% speed; invulnerable during burst; devastates anything in path.' },
    ],
  },
  'impact-transfer-boost': {
    id: 103,
    slug: 'impact-transfer-boost',
    name: 'Impact Transfer Boost',
    description: 'Converts incoming kinetic force into directional momentum for tactical repositioning.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: 'Passive', cooldown: '30 sec', effectDescription: 'Convert 20% of incoming impact into lateral movement boost.' },
      { level: 2, duration: 'Passive', cooldown: '28 sec', effectDescription: 'Convert 30% of impact; reduces knockback by 15%.' },
      { level: 3, duration: 'Passive', cooldown: '26 sec', effectDescription: 'Convert 40% of impact; can choose redirection angle.' },
      { level: 4, duration: 'Passive', cooldown: '24 sec', effectDescription: 'Convert 50% of impact; reduces knockback by 30%.' },
      { level: 5, duration: 'Passive', cooldown: '22 sec', effectDescription: 'Transfer works on explosions; convert 60% to movement.' },
      { level: 6, duration: 'Passive', cooldown: '20 sec', effectDescription: 'Can redirect into vertical leap; convert 70%.' },
      { level: 7, duration: 'Passive', cooldown: '18 sec', effectDescription: 'Convert 80% of impact; knockback immunity.' },
      { level: 8, duration: 'Passive', cooldown: '16 sec', effectDescription: 'Can share transfer boost with adjacent ally.' },
      { level: 9, duration: 'Passive', cooldown: '14 sec', effectDescription: 'Convert 90% of impact; minimal damage taken.' },
      { level: 10, duration: 'Passive', cooldown: '10 sec', effectDescription: 'Perfect Transfer: 100% conversion; impacts heal rather than damage.' },
    ],
  },
  'momentum-shift': {
    id: 104,
    slug: 'momentum-shift',
    name: 'Momentum Shift',
    description: 'Inertial manipulation system that instantly redirects movement vector without velocity loss.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: 'Instant', cooldown: '20 sec', effectDescription: 'Change movement direction by up to 45° without losing speed.' },
      { level: 2, duration: 'Instant', cooldown: '18 sec', effectDescription: 'Direction change up to 60°; +5% speed on shift.' },
      { level: 3, duration: 'Instant', cooldown: '16 sec', effectDescription: 'Direction change up to 90°; +10% speed on shift.' },
      { level: 4, duration: 'Instant', cooldown: '14 sec', effectDescription: 'Can shift mid-jump; direction change 120°.' },
      { level: 5, duration: 'Instant', cooldown: '12 sec', effectDescription: 'Direction change 150°; +15% speed; briefly confuses targeting.' },
      { level: 6, duration: 'Instant', cooldown: '10 sec', effectDescription: 'Full 180° reversal possible; +20% speed.' },
      { level: 7, duration: 'Instant', cooldown: '8 sec', effectDescription: 'Can shift twice in rapid succession.' },
      { level: 8, duration: 'Instant', cooldown: '6 sec', effectDescription: 'Shift generates brief decoy continuing original direction.' },
      { level: 9, duration: 'Instant', cooldown: '5 sec', effectDescription: 'Any angle + vertical component; +25% speed.' },
      { level: 10, duration: 'Instant', cooldown: '3 sec', effectDescription: 'Reality Slide: Instant omnidirectional shift; +50% speed; enemies cannot track.' },
    ],
  },
  'momentum-recenter-protocol': {
    id: 105,
    slug: 'momentum-recenter-protocol',
    name: 'Momentum Recenter Protocol',
    description: 'Neural-kinetic stabilization routine that instantly halts all movement and centers the user.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: 'Instant', cooldown: '25 sec', effectDescription: 'Instantly halt movement; +5% accuracy for 2 sec.' },
      { level: 2, duration: 'Instant', cooldown: '23 sec', effectDescription: 'Halt + stabilize; +10% accuracy for 3 sec.' },
      { level: 3, duration: 'Instant', cooldown: '21 sec', effectDescription: 'Negates fall damage when activated; +15% accuracy.' },
      { level: 4, duration: 'Instant', cooldown: '19 sec', effectDescription: 'Creates stable firing platform; +20% accuracy for 4 sec.' },
      { level: 5, duration: 'Instant', cooldown: '17 sec', effectDescription: 'Cancels stagger/stun effects on activation; +25% accuracy.' },
      { level: 6, duration: 'Instant', cooldown: '15 sec', effectDescription: 'Brief immovability (cannot be pushed); +30% accuracy.' },
      { level: 7, duration: 'Instant', cooldown: '13 sec', effectDescription: 'Can recenter mid-air; +35% accuracy for 5 sec.' },
      { level: 8, duration: 'Instant', cooldown: '11 sec', effectDescription: 'Recenter pulse affects nearby allies; +40% accuracy.' },
      { level: 9, duration: 'Instant', cooldown: '9 sec', effectDescription: 'Negates all momentum-based debuffs; +45% accuracy.' },
      { level: 10, duration: 'Instant', cooldown: '6 sec', effectDescription: 'Perfect Stillness: Complete stability; +60% accuracy; immune to displacement for 3 sec.' },
    ],
  },
  'braced-fire-stance': {
    id: 106,
    slug: 'braced-fire-stance',
    name: 'Braced Fire Stance',
    description: 'Combat posture optimization that trades mobility for enhanced weapon stability.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '10 sec', cooldown: '45 sec', effectDescription: 'Plant feet to reduce recoil by 15%; movement -50%.' },
      { level: 2, duration: '12 sec', cooldown: '42 sec', effectDescription: 'Recoil -20%; weapon sway eliminated.' },
      { level: 3, duration: '14 sec', cooldown: '39 sec', effectDescription: 'Recoil -25%; +10% accuracy.' },
      { level: 4, duration: '16 sec', cooldown: '36 sec', effectDescription: 'Recoil -30%; movement penalty reduced to -40%.' },
      { level: 5, duration: '18 sec', cooldown: '33 sec', effectDescription: 'Recoil -35%; +15% accuracy; can pivot slowly.' },
      { level: 6, duration: '20 sec', cooldown: '30 sec', effectDescription: 'Recoil -40%; +20% accuracy; suppression bonus.' },
      { level: 7, duration: '22 sec', cooldown: '27 sec', effectDescription: 'Recoil -45%; movement penalty -30%.' },
      { level: 8, duration: '25 sec', cooldown: '24 sec', effectDescription: 'Recoil -50%; +25% accuracy; reduced flinch.' },
      { level: 9, duration: '28 sec', cooldown: '20 sec', effectDescription: 'Recoil -55%; heavy weapons feel light.' },
      { level: 10, duration: '35 sec', cooldown: '15 sec', effectDescription: 'Iron Mountain: Zero recoil; perfect accuracy; can slow-walk while braced.' },
    ],
  },
  'hardpoint-brace-stance': {
    id: 107,
    slug: 'hardpoint-brace-stance',
    name: 'Hardpoint Brace Stance',
    description: 'Defensive anchor position that locks the user in place for maximum damage resistance.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '8 sec', cooldown: '50 sec', effectDescription: 'Lock position; +20% damage resistance; cannot move.' },
      { level: 2, duration: '10 sec', cooldown: '47 sec', effectDescription: '+25% damage resistance; reduced stagger.' },
      { level: 3, duration: '12 sec', cooldown: '44 sec', effectDescription: '+30% damage resistance; immune to knockback.' },
      { level: 4, duration: '14 sec', cooldown: '41 sec', effectDescription: '+35% damage resistance; allies behind gain cover bonus.' },
      { level: 5, duration: '16 sec', cooldown: '38 sec', effectDescription: '+40% damage resistance; can fire back while braced.' },
      { level: 6, duration: '18 sec', cooldown: '35 sec', effectDescription: '+45% damage resistance; taunt nearby enemies.' },
      { level: 7, duration: '20 sec', cooldown: '32 sec', effectDescription: '+50% damage resistance; reflect 10% of damage.' },
      { level: 8, duration: '22 sec', cooldown: '28 sec', effectDescription: '+55% damage resistance; immunity to critical hits.' },
      { level: 9, duration: '25 sec', cooldown: '24 sec', effectDescription: '+60% damage resistance; heal 1% HP/sec.' },
      { level: 10, duration: '30 sec', cooldown: '20 sec', effectDescription: 'Immovable Object: +80% damage resistance; reflect 25% damage; regen 3% HP/sec.' },
    ],
  },
  'brace-lock-stance': {
    id: 108,
    slug: 'brace-lock-stance',
    name: 'Brace Lock Stance',
    description: 'Emergency stability protocol that magnetically locks the user to any surface.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '6 sec', cooldown: '40 sec', effectDescription: 'Lock to floor; cannot be moved by any force.' },
      { level: 2, duration: '8 sec', cooldown: '37 sec', effectDescription: 'Lock to any metallic surface including walls.' },
      { level: 3, duration: '10 sec', cooldown: '34 sec', effectDescription: 'Lock to any solid surface; +10% damage resistance.' },
      { level: 4, duration: '12 sec', cooldown: '31 sec', effectDescription: 'Can lock upside down; +15% damage resistance.' },
      { level: 5, duration: '14 sec', cooldown: '28 sec', effectDescription: 'Lock grants perfect stability for sniper shots; +20% DR.' },
      { level: 6, duration: '16 sec', cooldown: '25 sec', effectDescription: 'Can lock to moving vehicles; +25% damage resistance.' },
      { level: 7, duration: '18 sec', cooldown: '22 sec', effectDescription: 'Lock negates environmental hazards; +30% DR.' },
      { level: 8, duration: '20 sec', cooldown: '19 sec', effectDescription: 'Can bring one ally into lock field; +35% DR.' },
      { level: 9, duration: '22 sec', cooldown: '16 sec', effectDescription: 'Lock works in zero-G; +40% damage resistance.' },
      { level: 10, duration: '30 sec', cooldown: '12 sec', effectDescription: 'Absolute Anchor: Lock to anything; immune to all movement; +60% DR; share with squad.' },
    ],
  },
  'combat-extraction-route-planner': {
    id: 109,
    slug: 'combat-extraction-route-planner',
    name: 'Combat Extraction Route Planner',
    description: 'Tactical AI that calculates optimal escape paths through hostile territory in real-time.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '30 sec', cooldown: '90 sec', effectDescription: 'Highlights basic escape route on HUD; +5% speed on route.' },
      { level: 2, duration: '35 sec', cooldown: '85 sec', effectDescription: 'Shows cover points along route; +10% speed.' },
      { level: 3, duration: '40 sec', cooldown: '80 sec', effectDescription: 'Route updates dynamically; +15% speed on route.' },
      { level: 4, duration: '45 sec', cooldown: '75 sec', effectDescription: 'Identifies enemy blind spots; +20% speed; reduced detection.' },
      { level: 5, duration: '50 sec', cooldown: '70 sec', effectDescription: 'Multiple route options shown; +25% speed.' },
      { level: 6, duration: '55 sec', cooldown: '65 sec', effectDescription: 'Predicts enemy patrol patterns; +30% speed.' },
      { level: 7, duration: '60 sec', cooldown: '60 sec', effectDescription: 'Includes vehicle escape options; +35% speed.' },
      { level: 8, duration: '70 sec', cooldown: '55 sec', effectDescription: 'Route shared with squad; +40% speed.' },
      { level: 9, duration: '80 sec', cooldown: '50 sec', effectDescription: 'Predicts environmental hazard timing; +45% speed.' },
      { level: 10, duration: '120 sec', cooldown: '40 sec', effectDescription: 'Perfect Escape: 100% accurate path; +60% speed; enemies cannot intercept.' },
    ],
  },
  'breach-advance-protocol': {
    id: 110,
    slug: 'breach-advance-protocol',
    name: 'Breach Advance Protocol',
    description: 'Aggressive entry technique that combines door breach with immediate room control.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '4 sec', cooldown: '60 sec', effectDescription: 'Breach door + 2m advance; +20% damage for 4 sec.' },
      { level: 2, duration: '5 sec', cooldown: '55 sec', effectDescription: 'Breach stuns enemies within 3m; +25% damage.' },
      { level: 3, duration: '6 sec', cooldown: '50 sec', effectDescription: 'Auto-target first enemy in room; +30% damage.' },
      { level: 4, duration: '7 sec', cooldown: '45 sec', effectDescription: 'Breach any door type; stun radius 4m; +35% damage.' },
      { level: 5, duration: '8 sec', cooldown: '40 sec', effectDescription: 'Flash component blinds room; +40% damage.' },
      { level: 6, duration: '9 sec', cooldown: '35 sec', effectDescription: 'Breach through walls (thin); +45% damage.' },
      { level: 7, duration: '10 sec', cooldown: '30 sec', effectDescription: 'Team breach: allies get bonus too; +50% damage.' },
      { level: 8, duration: '12 sec', cooldown: '25 sec', effectDescription: 'Breach creates smoke cover; +55% damage.' },
      { level: 9, duration: '14 sec', cooldown: '22 sec', effectDescription: 'Breach through reinforced walls; +60% damage.' },
      { level: 10, duration: '20 sec', cooldown: '18 sec', effectDescription: 'Shock Assault: Breach anything; room-wide stun; +100% damage for 3 sec.' },
    ],
  },
  'mobility-treatment-assist': {
    id: 111,
    slug: 'mobility-treatment-assist',
    name: 'Mobility Treatment Assist',
    description: 'Emergency locomotion support that helps wounded allies maintain combat mobility.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '15 sec', cooldown: '60 sec', effectDescription: 'Help wounded ally move at 50% speed.' },
      { level: 2, duration: '18 sec', cooldown: '55 sec', effectDescription: 'Wounded ally moves at 60% speed; minor healing.' },
      { level: 3, duration: '21 sec', cooldown: '50 sec', effectDescription: 'Ally moves at 70% speed; stabilize bleeding.' },
      { level: 4, duration: '24 sec', cooldown: '45 sec', effectDescription: 'Ally moves at 80% speed; pain suppression.' },
      { level: 5, duration: '27 sec', cooldown: '40 sec', effectDescription: 'Can assist two allies; 85% speed.' },
      { level: 6, duration: '30 sec', cooldown: '35 sec', effectDescription: 'Ally moves at 90% speed; moderate healing.' },
      { level: 7, duration: '35 sec', cooldown: '30 sec', effectDescription: 'Ally moves at 100% speed while assisted.' },
      { level: 8, duration: '40 sec', cooldown: '25 sec', effectDescription: 'Can carry downed ally while moving at 80%.' },
      { level: 9, duration: '45 sec', cooldown: '22 sec', effectDescription: 'Assist grants damage resistance to ally.' },
      { level: 10, duration: '60 sec', cooldown: '18 sec', effectDescription: 'Combat Medic Mode: Full ally mobility; continuous healing; both can fight.' },
    ],
  },
};
