// ============================================================
// PERCEPTION & TARGETING ABILITIES
// Predictive, scanning, awareness, threat mapping, precision
// ============================================================

import { ExportedAbility } from './types';

export const PERCEPTION_TARGETING_ABILITIES: Record<string, ExportedAbility> = {
  'proximity-threat-map': {
    id: 18,
    slug: 'proximity-threat-map',
    name: 'Proximity Threat Map',
    description: 'Neural-spatial analysis suite that generates a high-resolution tactical overlay of nearby hostiles.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '6 sec', cooldown: '6 min', effectDescription: 'Generates basic local threat pings with directional arrows for hostiles within 25 m; +2.5% ambush effectiveness.' },
      { level: 2, duration: '7 sec', cooldown: '5 min 45 sec', effectDescription: 'Adds short-range vision-cone visualization and smoother enemy-position updates; +5% ambush effectiveness.' },
      { level: 3, duration: '8 sec', cooldown: '5 min 30 sec', effectDescription: 'Displays slow-moving path projections for tracked enemies; +7.5% ambush effectiveness.' },
      { level: 4, duration: '9 sec', cooldown: '5 min 15 sec', effectDescription: 'Expands detection radius to 30 m and tightens positional accuracy; +10% ambush effectiveness.' },
      { level: 5, duration: '10 sec', cooldown: '5 min', effectDescription: 'Adds real-time acoustic signatures and line-of-sound estimation; +12.5% ambush effectiveness.' },
      { level: 6, duration: '12 sec', cooldown: '4 min 30 sec', effectDescription: 'Predictive movement modeling updates enemy path vectors in 0.3-second increments; +15% ambush effectiveness.' },
      { level: 7, duration: '14 sec', cooldown: '4 min', effectDescription: 'Highlights blind spots, dead angles, and optimal ambush points as HUD markers; +17.5% ambush effectiveness.' },
      { level: 8, duration: '16 sec', cooldown: '3 min 30 sec', effectDescription: 'Extends detection to 40 m and adds thermal-noise estimation for partially obscured targets; +20% ambush effectiveness.' },
      { level: 9, duration: '18 sec', cooldown: '3 min', effectDescription: 'Integrates environmental occlusion analysis, outlining terrain that blocks sightlines or sound propagation; +22.5% ambush effectiveness.' },
      { level: 10, duration: '20 sec', cooldown: '2 min 30 sec', effectDescription: 'Full threat-map suite with continuous enemy vision cones, movement prediction, acoustic reach, and dynamic ambush-lane optimization; +25% ambush effectiveness.' },
    ],
  },
  'tactical-analysis-protocol': {
    id: 20,
    slug: 'tactical-analysis-protocol',
    name: 'Tactical Analysis Protocol',
    description: 'Long-range neural-inspection module that evaluates the threat level, classification, and combat rating of distant targets.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '4 sec', cooldown: '3 min', effectDescription: 'Scans a single target up to 50 m; displays broad threat rating (Low / Moderate / High).' },
      { level: 2, duration: '5 sec', cooldown: '2 min 45 sec', effectDescription: 'Adds approximate level range (+/- 5 levels) for targets within 75 m.' },
      { level: 3, duration: '6 sec', cooldown: '2 min 30 sec', effectDescription: 'Extends range to 100 m and identifies target type (humanoid / fauna / synthetic).' },
      { level: 4, duration: '7 sec', cooldown: '2 min 15 sec', effectDescription: 'Displays approximate level (+/- 3 levels) for targets within 150 m; prevents scanning of users with equal or higher scan-tier.' },
      { level: 5, duration: '9 sec', cooldown: '2 min', effectDescription: 'Adds species/variant name and threat subtype (e.g., melee/ranged/support) at 200 m.' },
      { level: 6, duration: '11 sec', cooldown: '1 min 45 sec', effectDescription: 'Improves level accuracy (+/- 1 level) and extends range to 275 m.' },
      { level: 7, duration: '13 sec', cooldown: '1 min 30 sec', effectDescription: 'Reads exact level for targets equal or lower tier; identifies elite variants at 350 m.' },
      { level: 8, duration: '15 sec', cooldown: '1 min 15 sec', effectDescription: 'Extends range to 425 m and reveals exact level for all targets not protected by higher-tier analysis tools.' },
      { level: 9, duration: '17 sec', cooldown: '1 min', effectDescription: 'Displays additional classification data (role, behavior type, aggression index) up to 475 m.' },
      { level: 10, duration: '20 sec', cooldown: '45 sec', effectDescription: 'Full identification suite: exact level, species, subtype, threat designation, and behavioral profile up to 500 m.' },
    ],
  },
  'combat-predictive-analysis': {
    id: 21,
    slug: 'combat-predictive-analysis',
    name: 'Combat Predictive Analysis',
    description: 'Advanced combat-forecast module that models behavior, attack timing, weak-point exposure, and equipment capabilities.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '6 sec', cooldown: '4 min', effectDescription: 'Predicts basic attack intent (ranged/melee/defensive) for targets within 20 m.' },
      { level: 2, duration: '7 sec', cooldown: '3 min 45 sec', effectDescription: 'Adds movement-likelihood vectors showing probable next steps within 25 m.' },
      { level: 3, duration: '8 sec', cooldown: '3 min 30 sec', effectDescription: 'Identifies visible cybernetics and augmentations, tagging structural weak spots.' },
      { level: 4, duration: '9 sec', cooldown: '3 min 15 sec', effectDescription: 'Profiles armor density (light/medium/heavy) and notes material vulnerabilities.' },
      { level: 5, duration: '10 sec', cooldown: '3 min', effectDescription: 'Evaluates enemy weapon class, effective range, and reload/overheat likelihood within 45 m.' },
      { level: 6, duration: '12 sec', cooldown: '2 min 45 sec', effectDescription: 'Predicts dodge/evade behavior and marks likely flanking angles.' },
      { level: 7, duration: '14 sec', cooldown: '2 min 30 sec', effectDescription: 'Shows estimated damage windows; moments when target is less guarded or off-balance.' },
      { level: 8, duration: '16 sec', cooldown: '2 min 15 sec', effectDescription: 'Models short-term attack patterns (next 1–2 actions) with timing indicators.' },
      { level: 9, duration: '18 sec', cooldown: '2 min', effectDescription: 'Displays weak-point exposure timing and counterattack intervals.' },
      { level: 10, duration: '20 sec', cooldown: '90 sec', effectDescription: 'Full predictive-combat suite: attack forecasts, movement probabilities, cybernetic stress points, weapon failure chances, and optimal engagement timing.' },
    ],
  },
  'peripheral-target-acquisition': {
    id: 35,
    slug: 'peripheral-target-acquisition',
    name: 'Peripheral Target Acquisition',
    description: 'Neural-optical overlay that expands situational awareness by tracking secondary threats in the user\'s periphery and predicting their behavior.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '14 sec', cooldown: '6 min', effectDescription: 'Highlights secondary threats in a 30-degree cone near the primary sightline with -5% prediction error.' },
      { level: 2, duration: '17 sec', cooldown: '5 min 24 sec', effectDescription: 'Adds directional HUD arrows indicating off-screen threat movements.' },
      { level: 3, duration: '19 sec', cooldown: '4 min 50 sec', effectDescription: 'Enables simultaneous tracking of 1 additional secondary target.' },
      { level: 4, duration: '22 sec', cooldown: '4 min 20 sec', effectDescription: 'Provides audiovisual early-warning pings for flank attempts.' },
      { level: 5, duration: '24 sec', cooldown: '3 min 55 sec', effectDescription: 'Refines motion prediction algorithms, reducing error by -10%.' },
      { level: 6, duration: '26 sec', cooldown: '3 min 30 sec', effectDescription: 'Assigns threat priority colors based on weapon lethality and aggression.' },
      { level: 7, duration: '29 sec', cooldown: '3 min 10 sec', effectDescription: 'Enables simultaneous tracking of 2 additional secondary targets (Total +2).' },
      { level: 8, duration: '31 sec', cooldown: '2 min 50 sec', effectDescription: 'Detects and highlights enemy reload cycles and weapon jams.' },
      { level: 9, duration: '34 sec', cooldown: '2 min 35 sec', effectDescription: 'Instant target re-acquisition after rapid head movement or turning.' },
      { level: 10, duration: '36 sec', cooldown: '2 min 20 sec', effectDescription: 'Projects movement ghosts showing the next two likely position nodes for all tracked targets.' },
    ],
  },
  'predator-mark': {
    id: 39,
    slug: 'predator-mark',
    name: 'Predator Mark',
    description: 'Neural-tagging protocol that locks onto a specific target, highlighting their silhouette through obstacles and analyzing structural weak points.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '20 sec', cooldown: '5 min', effectDescription: 'Highlights selected target with a red neural-outline; +5% damage to marked target.' },
      { level: 2, duration: '22 sec', cooldown: '4 min 30 sec', effectDescription: 'Target outline remains visible through thin cover (smoke, foliage, wood).' },
      { level: 3, duration: '24 sec', cooldown: '4 min 05 sec', effectDescription: 'Analyzes target gait to predict sudden directional changes; +7% damage.' },
      { level: 4, duration: '26 sec', cooldown: '3 min 40 sec', effectDescription: 'Highlights armor fracture points; critical hit chance +5% against marked target.' },
      { level: 5, duration: '30 sec', cooldown: '3 min 20 sec', effectDescription: 'Maintains target lock even if visual contact is lost for up to 3 seconds.' },
      { level: 6, duration: '34 sec', cooldown: '3 min', effectDescription: 'Interface projects a "lead indicator" ghost for moving targets; +10% damage.' },
      { level: 7, duration: '38 sec', cooldown: '2 min 40 sec', effectDescription: 'Full wall-penetration tracking: Silhouette visible through solid walls (up to 1m thick).' },
      { level: 8, duration: '42 sec', cooldown: '2 min 20 sec', effectDescription: 'Vulnerability Analysis: Critical hit damage increased by 25% against marked target.' },
      { level: 9, duration: '46 sec', cooldown: '2 min', effectDescription: 'Target Sharing: Relays neural tag coordinates to squadmates\' HUDs.' },
      { level: 10, duration: '50 sec', cooldown: '1 min 45 sec', effectDescription: 'Apex Predator Suite: Real-time absolute tracking through any obstacle; +20% damage; critical hits cripple target movement.' },
    ],
  },
  'perfect-line-shot': {
    id: 43,
    slug: 'perfect-line-shot',
    name: 'Perfect Line Shot',
    description: 'Predictive aim-assist algorithm that draws the optimal firing vector through partial cover or moving threats.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '8 sec', cooldown: '3 min', effectDescription: 'Draws a firing line on HUD showing 100% accuracy path; ignores 10% of target cover.' },
      { level: 2, duration: '9 sec', cooldown: '2 min 42 sec', effectDescription: 'Predicts target movement along the line; shots lead the target automatically.' },
      { level: 3, duration: '10 sec', cooldown: '2 min 25 sec', effectDescription: 'Ignores 25% of target cover/armor rating.' },
      { level: 4, duration: '11 sec', cooldown: '2 min 10 sec', effectDescription: 'Highlights "collateral lines" where one shot can hit two aligned targets.' },
      { level: 5, duration: '12 sec', cooldown: '1 min 55 sec', effectDescription: 'Shots fired along the Perfect Line deal +15% critical damage.' },
      { level: 6, duration: '14 sec', cooldown: '1 min 45 sec', effectDescription: 'Ignores 50% of target cover/armor rating.' },
      { level: 7, duration: '16 sec', cooldown: '1 min 35 sec', effectDescription: 'Phase-Rounds: Projectiles pass through thin walls/objects to hit marked targets.' },
      { level: 8, duration: '18 sec', cooldown: '1 min 25 sec', effectDescription: 'Critical Hit Chance increased by 50% for shots on the line.' },
      { level: 9, duration: '20 sec', cooldown: '1 min 15 sec', effectDescription: 'Ignores 100% of cover (shots penetrate barriers without damage loss).' },
      { level: 10, duration: '25 sec', cooldown: '1 min', effectDescription: 'Railgun Protocol: Shots are instant-hit (hitscan) with infinite penetration depth along the line.' },
    ],
  },
  'thermal-signature-lock': {
    id: 71,
    slug: 'thermal-signature-lock',
    name: 'Thermal Signature Lock',
    description: 'Multispectral targeting suite that highlights heat sinks, vents, and overheating components on enemy machinery.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '10 sec', cooldown: '4 min', effectDescription: 'Highlights heat sinks and vents; +5% Fire damage to targets.' },
      { level: 2, duration: '12 sec', cooldown: '3 min 36 sec', effectDescription: 'Targeting hot spots bypasses 10% of energy shielding.' },
      { level: 3, duration: '14 sec', cooldown: '3 min 15 sec', effectDescription: 'Highlights overheating weapons; striking them causes weapon jam/failure.' },
      { level: 4, duration: '16 sec', cooldown: '2 min 55 sec', effectDescription: 'Predicts when enemy shields will cycle/vent heat.' },
      { level: 5, duration: '18 sec', cooldown: '2 min 35 sec', effectDescription: 'Combustion: Hitting thermal weak points has 20% chance to ignite target.' },
      { level: 6, duration: '20 sec', cooldown: '2 min 20 sec', effectDescription: 'Tracks invisible units via heat trace.' },
      { level: 7, duration: '22 sec', cooldown: '2 min 05 sec', effectDescription: 'Critical hits on vents cause internal component damage (Slow/Stun).' },
      { level: 8, duration: '25 sec', cooldown: '1 min 50 sec', effectDescription: 'Thermal Shock: Switching from Cryo to Pyro damage on locked target deals +50% shock damage.' },
      { level: 9, duration: '28 sec', cooldown: '1 min 35 sec', effectDescription: 'Chain Ignition: Burning targets spread heat to nearby locked enemies.' },
      { level: 10, duration: '35 sec', cooldown: '1 min 20 sec', effectDescription: 'Core Meltdown: Hitting the primary heat sink bypasses all defenses and deals True Damage; lethal to robotic/vehicle targets.' },
    ],
  },
  'structural-integrity-scan': {
    id: 87,
    slug: 'structural-integrity-scan',
    name: 'Structural Integrity Scan',
    description: 'Diagnostic overlay that highlights stress fractures, heat warping, corrosion, and material fatigue in machinery and structures.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '15 sec', cooldown: '4 min', effectDescription: 'Highlights surface-level cracks and rust; identifies material type.' },
      { level: 2, duration: '17 sec', cooldown: '3 min 36 sec', effectDescription: 'Detects internal stress fractures up to 5cm deep.' },
      { level: 3, duration: '19 sec', cooldown: '3 min 15 sec', effectDescription: 'Estimates "Time to Failure" for damaged equipment.' },
      { level: 4, duration: '21 sec', cooldown: '2 min 55 sec', effectDescription: 'Visualizes heat warping and thermal stress points.' },
      { level: 5, duration: '23 sec', cooldown: '2 min 35 sec', effectDescription: 'Highlights weak points on enemy vehicles (Fuel lines/Ammo racks).' },
      { level: 6, duration: '25 sec', cooldown: '2 min 20 sec', effectDescription: 'Penetrates shielding to scan internal components.' },
      { level: 7, duration: '27 sec', cooldown: '2 min 05 sec', effectDescription: 'Can scan structural stability of buildings/floors.' },
      { level: 8, duration: '30 sec', cooldown: '1 min 50 sec', effectDescription: 'Identifies specific alloy composition for salvage value.' },
      { level: 9, duration: '35 sec', cooldown: '1 min 35 sec', effectDescription: '3D Schematic: Generates a rotatable model of the object.' },
      { level: 10, duration: '40 sec', cooldown: '1 min 20 sec', effectDescription: 'Deep Scan: Complete transparency; reveals every bolt, wire, and micro-fracture; +20% Repair Speed on scanned object.' },
    ],
  },
  'explosive-yield-predictor': {
    id: 91,
    slug: 'explosive-yield-predictor',
    name: 'Explosive Yield Predictor',
    description: 'Physics simulation engine that projects blast radii, shockwave propagation, and structural collapse probabilities on the HUD.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '14 sec', cooldown: '4 min', effectDescription: 'Visualizes blast radius of equipped explosives.' },
      { level: 2, duration: '16 sec', cooldown: '3 min 36 sec', effectDescription: 'Highlights "Safe Zones" within the blast area (behind cover).' },
      { level: 3, duration: '18 sec', cooldown: '3 min 15 sec', effectDescription: 'Calculates structural collapse direction.' },
      { level: 4, duration: '20 sec', cooldown: '2 min 55 sec', effectDescription: 'Explosive Damage +15% due to optimal placement.' },
      { level: 5, duration: '22 sec', cooldown: '2 min 35 sec', effectDescription: 'Shaped Charge: Shows how to direct blast force to breach without collateral damage.' },
      { level: 6, duration: '24 sec', cooldown: '2 min 20 sec', effectDescription: 'Predicts chain reactions (e.g., exploding barrels).' },
      { level: 7, duration: '26 sec', cooldown: '2 min 05 sec', effectDescription: 'Highlights weak points for "Economy Demolition" (using less explosive).' },
      { level: 8, duration: '28 sec', cooldown: '1 min 50 sec', effectDescription: 'Explosive Damage +30%.' },
      { level: 9, duration: '30 sec', cooldown: '1 min 35 sec', effectDescription: 'Can analyze enemy explosives to find disarm method.' },
      { level: 10, duration: '35 sec', cooldown: '1 min 20 sec', effectDescription: 'Surgical Destruction: Explosives deal 100% damage to intended target and 0% to surrounding environment/allies if placed on marker.' },
    ],
  },
  'tracking-vector-overlay': {
    id: 40,
    slug: 'tracking-vector-overlay',
    name: 'Tracking Vector Overlay',
    description: 'Heuristic forensics engine that visualizes recent enemy movement, thermal decay, and probable trajectory on the environmental HUD.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '30 sec', cooldown: '4 min', effectDescription: 'Displays basic luminescent footprints and disturbed soil highlights.' },
      { level: 2, duration: '35 sec', cooldown: '3 min 35 sec', effectDescription: 'Adds thermal residue analysis to determine how recently the target passed.' },
      { level: 3, duration: '40 sec', cooldown: '3 min 15 sec', effectDescription: 'Extends tracking range to 100m; highlights blood spatter with species identification.' },
      { level: 4, duration: '45 sec', cooldown: '2 min 55 sec', effectDescription: 'Calculates stride length and depth to estimate target weight and loadout.' },
      { level: 5, duration: '50 sec', cooldown: '2 min 40 sec', effectDescription: 'Projected Trajectory: Displays a dashed line estimating the target\'s destination.' },
      { level: 6, duration: '60 sec', cooldown: '2 min 25 sec', effectDescription: 'Scents/Pheromones are visualized as color-coded air currents.' },
      { level: 7, duration: '70 sec', cooldown: '2 min 10 sec', effectDescription: 'Reconstructs a wireframe "Ghost" of the target performing their last action at the scene.' },
      { level: 8, duration: '80 sec', cooldown: '1 min 55 sec', effectDescription: 'Highlights concealed traps, tripwires, and ambush spots along the path.' },
      { level: 9, duration: '90 sec', cooldown: '1 min 40 sec', effectDescription: 'Real-time update: If the tracked target is within 200m, a ping reveals their exact location.' },
      { level: 10, duration: '120 sec', cooldown: '1 min 30 sec', effectDescription: 'Omniscient Tracker: Visualizes the entire history of the area (up to 1 hour); enemies cannot hide their trails regardless of stealth capabilities.' },
    ],
  },
  'ricochet-planner': {
    id: 48,
    slug: 'ricochet-planner',
    name: 'Ricochet Planner',
    description: 'Real-time geometry engine that calculates bounce trajectories for angling shots around corners or off surfaces.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '10 sec', cooldown: '5 min', effectDescription: 'Calculates 1 bounce trajectory; projectile retains 80% damage.' },
      { level: 2, duration: '12 sec', cooldown: '4 min 30 sec', effectDescription: 'HUD highlights surfaces with high ricochet potential (metal, concrete).' },
      { level: 3, duration: '14 sec', cooldown: '4 min', effectDescription: 'Calculates 2 bounce trajectories; projectile retains 90% damage.' },
      { level: 4, duration: '16 sec', cooldown: '3 min 35 sec', effectDescription: 'Auto-adjusts aim to hit the bounce angle even if aim is slightly off.' },
      { level: 5, duration: '18 sec', cooldown: '3 min 10 sec', effectDescription: 'Ricochet shots hit target form the side/rear, bypassing directional shields.' },
      { level: 6, duration: '20 sec', cooldown: '2 min 50 sec', effectDescription: 'Calculates 3 bounce trajectories; projectile gains velocity (100% damage).' },
      { level: 7, duration: '22 sec', cooldown: '2 min 30 sec', effectDescription: 'Split-Shot: Hitting a corner edge splits the bullet into two trajectories.' },
      { level: 8, duration: '25 sec', cooldown: '2 min 10 sec', effectDescription: 'Ricochets auto-seek targets within 2 meters of the bounce point.' },
      { level: 9, duration: '28 sec', cooldown: '1 min 50 sec', effectDescription: 'Damage increased by 20% per bounce.' },
      { level: 10, duration: '30 sec', cooldown: '1 min 30 sec', effectDescription: 'Geometry God: Unlimited bounces within duration. Bullets do not stop until they hit flesh; room-clearing capability.' },
    ],
  },
  'zone-lock-indicator': {
    id: 68,
    slug: 'zone-lock-indicator',
    name: 'Zone Lock Indicator',
    description: 'Tactical overlay that highlights optimal suppression lanes and tracks enemy suppression meters.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '15 sec', cooldown: '5 min', effectDescription: 'Highlights optimal suppression lanes; enemies in lane marked.' },
      { level: 2, duration: '18 sec', cooldown: '4 min 30 sec', effectDescription: 'Suppressed enemies in zone suffer -10% accuracy.' },
      { level: 3, duration: '21 sec', cooldown: '4 min 05 sec', effectDescription: 'Zone width increased; highlights cover that is destructible.' },
      { level: 4, duration: '24 sec', cooldown: '3 min 40 sec', effectDescription: 'Enemies entering the zone are auto-tagged for the squad.' },
      { level: 5, duration: '27 sec', cooldown: '3 min 20 sec', effectDescription: 'Suppression Effect: Enemies in zone move 20% slower.' },
      { level: 6, duration: '30 sec', cooldown: '3 min', effectDescription: 'Bullet Magnetism: Shots fired into the zone drift slightly toward targets.' },
      { level: 7, duration: '33 sec', cooldown: '2 min 40 sec', effectDescription: 'Morale Break: Weak enemies in the zone may rout/flee.' },
      { level: 8, duration: '36 sec', cooldown: '2 min 20 sec', effectDescription: 'Damage to enemy cover in zone increased by 50%.' },
      { level: 9, duration: '40 sec', cooldown: '2 min', effectDescription: 'Pinning Fire: Critical hits root enemies in place for 1 second.' },
      { level: 10, duration: '50 sec', cooldown: '1 min 45 sec', effectDescription: 'Killbox: Enemies inside the zone take +20% damage from all sources; suppression effects are instant.' },
    ],
  },
  'split-target-routine': {
    id: 49,
    slug: 'split-target-routine',
    name: 'Split-Target Routine',
    description: 'Multi-thread targeting processor enabling independent tracking and firing upon multiple hostiles simultaneously.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '12 sec', cooldown: '4 min', effectDescription: 'Enables independent targeting of 2 hostiles; accuracy -10% on secondary.' },
      { level: 2, duration: '14 sec', cooldown: '3 min 36 sec', effectDescription: 'Removes accuracy penalty for secondary target.' },
      { level: 3, duration: '16 sec', cooldown: '3 min 15 sec', effectDescription: 'Neural division allows user to look one way and shoot another.' },
      { level: 4, duration: '18 sec', cooldown: '2 min 55 sec', effectDescription: 'Recoil damping optimized for dual-fire; rapid fire stability +20%.' },
      { level: 5, duration: '20 sec', cooldown: '2 min 35 sec', effectDescription: 'Can target 3 hostiles (requires fast switching or extra mechanical arms).' },
      { level: 6, duration: '22 sec', cooldown: '2 min 20 sec', effectDescription: 'Suppressive Fire: Targets under split-fire have reduced accuracy (-15%).' },
      { level: 7, duration: '24 sec', cooldown: '2 min 05 sec', effectDescription: 'Crossfire: Hitting one target with both guns simultaneously deals +30% damage.' },
      { level: 8, duration: '26 sec', cooldown: '1 min 50 sec', effectDescription: '360-degree awareness: Auto-fires at threats entering rear proximity.' },
      { level: 9, duration: '28 sec', cooldown: '1 min 35 sec', effectDescription: 'Movement speed +15% while engaging multiple targets.' },
      { level: 10, duration: '35 sec', cooldown: '1 min 20 sec', effectDescription: 'Gun Kata Core: Perfect multi-tasking. Can engage max targets visible on screen simultaneously with perfect accuracy; reloads are automatic.' },
    ],
  },
  'threat-rhythm-pulse': {
    id: 65,
    slug: 'threat-rhythm-pulse',
    name: 'Threat Rhythm Pulse',
    description: 'Predictive algorithm that analyzes enemy firing cadences to identify safe timing gaps for advancing under fire.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '12 sec', cooldown: '5 min', effectDescription: 'Visualizes enemy fire patterns; green zones indicate safe timing.' },
      { level: 2, duration: '14 sec', cooldown: '4 min 30 sec', effectDescription: 'Predicts enemy reloads 2 seconds in advance.' },
      { level: 3, duration: '16 sec', cooldown: '4 min 05 sec', effectDescription: 'Dodge Chance +15% against rhythmic fire (turrets/auto-fire).' },
      { level: 4, duration: '18 sec', cooldown: '3 min 40 sec', effectDescription: 'Highlights "Aggro" lines; shows who is aiming at you vs. allies.' },
      { level: 5, duration: '20 sec', cooldown: '3 min 20 sec', effectDescription: 'Adrenal Reflex: Auto-dodges the first fatal shot received.' },
      { level: 6, duration: '22 sec', cooldown: '3 min', effectDescription: 'Predicts grenade arcs and explosion radii.' },
      { level: 7, duration: '24 sec', cooldown: '2 min 40 sec', effectDescription: 'Syncs movement with enemy fire rate to become harder to track.' },
      { level: 8, duration: '27 sec', cooldown: '2 min 20 sec', effectDescription: 'Highlights "Friendly Fire" incidents in enemy ranks to exploit.' },
      { level: 9, duration: '30 sec', cooldown: '2 min', effectDescription: 'Counter-Rhythm: Firing during enemy gaps deals +20% damage.' },
      { level: 10, duration: '40 sec', cooldown: '1 min 45 sec', effectDescription: 'Flow State: The user perceives the battlefield as a predictable algorithm; +50% Evasion, +50% Movement Speed toward enemies.' },
    ],
  },
  'saturation-spread-assist': {
    id: 69,
    slug: 'saturation-spread-assist',
    name: 'Saturation Spread Assist',
    description: 'Fire-control override that micromanages trigger timing and barrel drift to create an inescapable wall of lead.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '12 sec', cooldown: '4 min', effectDescription: 'Visualizes bullet spread cone; allows widening/tightening via neural command.' },
      { level: 2, duration: '14 sec', cooldown: '3 min 36 sec', effectDescription: 'Ensures even distribution of shots across the cone (no gaps).' },
      { level: 3, duration: '16 sec', cooldown: '3 min 15 sec', effectDescription: 'Ammo conservation: Prevents firing if cone is empty of targets.' },
      { level: 4, duration: '18 sec', cooldown: '2 min 55 sec', effectDescription: 'Increases fire rate by 10% during saturation fire.' },
      { level: 5, duration: '20 sec', cooldown: '2 min 35 sec', effectDescription: 'Ricochet calculation: Missed shots bounce inward toward center of cone.' },
      { level: 6, duration: '22 sec', cooldown: '2 min 20 sec', effectDescription: 'Pattern Matching: Auto-adjusts spread to match enemy formation width.' },
      { level: 7, duration: '24 sec', cooldown: '2 min 05 sec', effectDescription: 'Suppressing hits reduce enemy cooldown regeneration.' },
      { level: 8, duration: '27 sec', cooldown: '1 min 50 sec', effectDescription: 'Extended Mags: Virtual ammo management effectively increases mag size by 25%.' },
      { level: 9, duration: '30 sec', cooldown: '1 min 35 sec', effectDescription: 'Targets hit by saturation fire are marked for artillery/grenades.' },
      { level: 10, duration: '40 sec', cooldown: '1 min 20 sec', effectDescription: 'Lead Wall: Maximum fire rate; bullets form a grid that is mathematically impossible to dodge without cover.' },
    ],
  },
  'infrared-penetration-sweep': {
    id: 73,
    slug: 'infrared-penetration-sweep',
    name: 'Infrared Penetration Sweep',
    description: 'High-intensity active IR pulse that maps heat signatures through smoke, fog, and light cover.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '8 sec', cooldown: '4 min', effectDescription: 'Pulse reveals heat signatures through smoke and thin concealment (20m).' },
      { level: 2, duration: '10 sec', cooldown: '3 min 36 sec', effectDescription: 'Range increased to 30m; distinguishes friend/foe/neutral.' },
      { level: 3, duration: '12 sec', cooldown: '3 min 15 sec', effectDescription: 'Sees through solid walls (wood/drywall).' },
      { level: 4, duration: '14 sec', cooldown: '2 min 55 sec', effectDescription: 'Highlights trap circuits and active power lines.' },
      { level: 5, duration: '16 sec', cooldown: '2 min 35 sec', effectDescription: 'Residual Analysis: Shows heat footprints of where enemies were 10s ago.' },
      { level: 6, duration: '18 sec', cooldown: '2 min 20 sec', effectDescription: 'Range increased to 50m; Penetrates concrete.' },
      { level: 7, duration: '20 sec', cooldown: '2 min 05 sec', effectDescription: 'Targets revealed take +10% damage from all sources.' },
      { level: 8, duration: '22 sec', cooldown: '1 min 50 sec', effectDescription: 'Detects cold-blooded/stealth targets via negative thermal contrast.' },
      { level: 9, duration: '25 sec', cooldown: '1 min 35 sec', effectDescription: 'Can focus pulse to "Flashbang" thermal optics of enemies, blinding them.' },
      { level: 10, duration: '30 sec', cooldown: '1 min 20 sec', effectDescription: 'Omni-Ocular: Full battlefield transparency; overlays structural weak points and enemy positions for entire squad; cannot be jammed.' },
    ],
  },
  'ally-cover-projection': {
    id: 77,
    slug: 'ally-cover-projection',
    name: 'Ally Cover Projection',
    description: 'Tactical overlay that identifies line-of-fire blockades, guiding the user to body-block damage for teammates.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '10 sec', cooldown: '4 min', effectDescription: 'Highlights Line-of-Sight blocks to protect specific allies.' },
      { level: 2, duration: '12 sec', cooldown: '3 min 36 sec', effectDescription: 'User hitbox effectively widens by 10% to intercept shots.' },
      { level: 3, duration: '14 sec', cooldown: '3 min 15 sec', effectDescription: 'Intercepting damage for an ally builds "Vengeance" charge.' },
      { level: 4, duration: '16 sec', cooldown: '2 min 55 sec', effectDescription: 'Highlights optimal path to intercept a moving threat.' },
      { level: 5, duration: '18 sec', cooldown: '2 min 35 sec', effectDescription: 'Guardian Dash: Movement speed +30% when moving towards an injured ally.' },
      { level: 6, duration: '20 sec', cooldown: '2 min 20 sec', effectDescription: 'Damage taken while body-blocking reduced by 15%.' },
      { level: 7, duration: '22 sec', cooldown: '2 min 05 sec', effectDescription: 'Projected Force: Allies standing behind user gain +10% Accuracy.' },
      { level: 8, duration: '25 sec', cooldown: '1 min 50 sec', effectDescription: 'User can deploy a physical tower shield to extend cover width.' },
      { level: 9, duration: '30 sec', cooldown: '1 min 35 sec', effectDescription: 'Damage taken while body-blocking reduced by 30%.' },
      { level: 10, duration: '40 sec', cooldown: '1 min 20 sec', effectDescription: 'Human Aegis: Any damage that would kill an adjacent ally is transferred to the user instead (capped at 50% of user HP).' },
    ],
  },
  'threat-absorption-matrix': {
    id: 85,
    slug: 'threat-absorption-matrix',
    name: 'Threat Absorption Matrix',
    description: 'Advanced threat-assessment engine that visually weighs incoming fire to optimize shield angling and armor sloping.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '15 sec', cooldown: '6 min', effectDescription: 'Visualizes threat levels; marks highest DPS enemy.' },
      { level: 2, duration: '18 sec', cooldown: '5 min 24 sec', effectDescription: 'Auto-angles armor to deflect the highest threat.' },
      { level: 3, duration: '21 sec', cooldown: '4 min 50 sec', effectDescription: 'Taunt Broadcast: Electronic warfare suite marks user as high-priority target to enemy AI.' },
      { level: 4, duration: '24 sec', cooldown: '4 min 20 sec', effectDescription: 'Analysis grants +15% defense against the marked target.' },
      { level: 5, duration: '27 sec', cooldown: '3 min 55 sec', effectDescription: 'Absorbing damage charges a counter-attack capacitor.' },
      { level: 6, duration: '30 sec', cooldown: '3 min 30 sec', effectDescription: 'Matrix predicts enemy focus fire; alerts squad to take cover.' },
      { level: 7, duration: '35 sec', cooldown: '3 min 10 sec', effectDescription: 'Defense +25% against marked target.' },
      { level: 8, duration: '40 sec', cooldown: '2 min 50 sec', effectDescription: 'Aggro Lock: Forces enemy targeting systems to lock onto user.' },
      { level: 9, duration: '45 sec', cooldown: '2 min 35 sec', effectDescription: 'Damage Conversion: 5% of incoming damage is converted to Energy.' },
      { level: 10, duration: '60 sec', cooldown: '2 min 15 sec', effectDescription: 'Black Hole: All enemy fire within 50m is magnetically pulled toward the user; User gains +80% Damage Reduction.' },
    ],
  },
  'rapid-sight-reacquisition': {
    id: 42,
    slug: 'rapid-sight-reacquisition',
    name: 'Rapid Sight Reacquisition',
    description: 'Optical feedback loop that auto-corrects aim point immediately after recoil, allowing for superhuman follow-up shot speed.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '12 sec', cooldown: '4 min', effectDescription: 'Auto-corrects aim point after recoil, speeding up follow-up shots by 15%.' },
      { level: 2, duration: '14 sec', cooldown: '3 min 35 sec', effectDescription: 'Reduces "visual noise" from muzzle flash and smoke in the optic feed.' },
      { level: 3, duration: '16 sec', cooldown: '3 min 15 sec', effectDescription: 'Follow-up shot speed increased by 25%.' },
      { level: 4, duration: '18 sec', cooldown: '2 min 55 sec', effectDescription: 'Snap-Targeting: Reticle magnetically "snaps" to the nearest enemy center-mass when ADS.' },
      { level: 5, duration: '20 sec', cooldown: '2 min 40 sec', effectDescription: 'Recoil recovery is instant for semi-automatic weapons.' },
      { level: 6, duration: '22 sec', cooldown: '2 min 25 sec', effectDescription: 'Follow-up shot speed increased by 40%.' },
      { level: 7, duration: '24 sec', cooldown: '2 min 10 sec', effectDescription: 'Peripheral Snap: Can instantly snap-aim to targets appearing in the 90-degree peripheral cone.' },
      { level: 8, duration: '26 sec', cooldown: '1 min 55 sec', effectDescription: 'Kill-Chain: Each successful hit increases the speed of the next reacquisition (stacking).' },
      { level: 9, duration: '28 sec', cooldown: '1 min 40 sec', effectDescription: 'Eliminates optic sway during rapid movement or jumping.' },
      { level: 10, duration: '30 sec', cooldown: '1 min 30 sec', effectDescription: 'Aimbot Protocol: Neural override performs frame-perfect target switching and recoil control; maximum fire rate achieved with zero accuracy loss.' },
    ],
  },
  'vital-tracking-pulse': {
    id: 54,
    slug: 'vital-tracking-pulse',
    name: 'Vital Tracking Pulse',
    description: 'Biometric sonar that pings local IFF tags to display real-time heart rate, blood pressure, and stress levels.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '10 sec', cooldown: '4 min', effectDescription: 'Reveals HP bars and heart rates of allies in 15m radius.' },
      { level: 2, duration: '12 sec', cooldown: '3 min 36 sec', effectDescription: 'Radius increased to 20m; detects abnormal stress levels.' },
      { level: 3, duration: '14 sec', cooldown: '3 min 15 sec', effectDescription: 'Displays status effects (poison, burn, radiation) on HUD.' },
      { level: 4, duration: '16 sec', cooldown: '2 min 55 sec', effectDescription: 'Alerts user when an ally drops below 50% HP.' },
      { level: 5, duration: '18 sec', cooldown: '2 min 35 sec', effectDescription: 'Can track vitals through walls/interference.' },
      { level: 6, duration: '20 sec', cooldown: '2 min 15 sec', effectDescription: 'Biometric Link: User gains small stamina boost based on squad health average.' },
      { level: 7, duration: '22 sec', cooldown: '2 min', effectDescription: 'Radius increased to 40m; detects enemy vitals if within 5m.' },
      { level: 8, duration: '25 sec', cooldown: '1 min 45 sec', effectDescription: 'Predicts ally "downed" state 3 seconds before it happens.' },
      { level: 9, duration: '28 sec', cooldown: '1 min 30 sec', effectDescription: 'Integration: Automatically triggers "Pain Response Dampener" on critical allies (if available).' },
      { level: 10, duration: '35 sec', cooldown: '1 min 15 sec', effectDescription: 'Squad Command: Full squad biometrics visible to all team members; +10% Squad Health regen.' },
    ],
  },
  'hazard-pulse-scan': {
    id: 78,
    slug: 'hazard-pulse-scan',
    name: 'Hazard Pulse Scan',
    description: 'Short-range sensor burst that detects environmental volatility, explosives, and structural weaknesses.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '8 sec', cooldown: '3 min', effectDescription: 'Highlights explosives and mines within 15m.' },
      { level: 2, duration: '10 sec', cooldown: '2 min 42 sec', effectDescription: 'Detects structural instability (falling rocks/weak floors).' },
      { level: 3, duration: '12 sec', cooldown: '2 min 25 sec', effectDescription: 'Identifies chemical/radiation pools.' },
      { level: 4, duration: '14 sec', cooldown: '2 min 10 sec', effectDescription: 'Highlights enemy "kill zones" (overlapping fields of fire).' },
      { level: 5, duration: '16 sec', cooldown: '1 min 55 sec', effectDescription: 'Can hack/disable simple proximity mines wirelessly.' },
      { level: 6, duration: '18 sec', cooldown: '1 min 45 sec', effectDescription: 'Predicts environmental reactions (e.g., shooting a barrel will cause collapse).' },
      { level: 7, duration: '20 sec', cooldown: '1 min 35 sec', effectDescription: 'Range increased to 40m.' },
      { level: 8, duration: '22 sec', cooldown: '1 min 25 sec', effectDescription: 'Scan data shared with squad; allies take -20% damage from hazards.' },
      { level: 9, duration: '25 sec', cooldown: '1 min 15 sec', effectDescription: 'Highlights ambush triggers and trapwires.' },
      { level: 10, duration: '30 sec', cooldown: '1 min', effectDescription: 'Clear Path: Highlights a perfectly safe route through any minefield or hazard zone; +20% Speed while following it.' },
    ],
  },
  'armor-stress-indicator': {
    id: 82,
    slug: 'armor-stress-indicator',
    name: 'Armor Stress Indicator',
    description: 'Diagnostic HUD that reveals failing integrity in own armor and optimal impact points on enemy armor.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '12 sec', cooldown: '4 min', effectDescription: 'Shows own armor integrity; highlights weakest plates.' },
      { level: 2, duration: '14 sec', cooldown: '3 min 36 sec', effectDescription: 'Predicts armor failure 3 seconds before break.' },
      { level: 3, duration: '16 sec', cooldown: '3 min 15 sec', effectDescription: 'Auto-adjusts posture to present strongest armor to enemy.' },
      { level: 4, duration: '18 sec', cooldown: '2 min 55 sec', effectDescription: 'Effective Armor Rating +10% due to optimal angling.' },
      { level: 5, duration: '20 sec', cooldown: '2 min 35 sec', effectDescription: 'Highlights enemy armor gaps created by user\'s attacks.' },
      { level: 6, duration: '22 sec', cooldown: '2 min 20 sec', effectDescription: 'Glancing Blows: 20% chance to deflect direct hits entirely.' },
      { level: 7, duration: '25 sec', cooldown: '2 min 05 sec', effectDescription: 'User gains critical hit chance against enemy weak plates.' },
      { level: 8, duration: '28 sec', cooldown: '1 min 50 sec', effectDescription: 'Emergency Lock: Can fuse broken armor joints to maintain protection (at cost of speed).' },
      { level: 9, duration: '32 sec', cooldown: '1 min 35 sec', effectDescription: 'Armor Rating +25%.' },
      { level: 10, duration: '40 sec', cooldown: '1 min 20 sec', effectDescription: 'Living Metal: Neural-link maximizes armor efficiency; effective Armor Rating +50%; armor cannot be broken or penetrated for duration.' },
    ],
  },
  'fault-path-analysis': {
    id: 90,
    slug: 'fault-path-analysis',
    name: 'Fault Path Analysis',
    description: 'Heuristic logic engine that traces electrical or data faults backward through a system to identify the physical root cause.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '18 sec', cooldown: '5 min', effectDescription: 'Highlights broken circuits or severed cables.' },
      { level: 2, duration: '20 sec', cooldown: '4 min 30 sec', effectDescription: 'Traces power flow to find drain/leakage.' },
      { level: 3, duration: '22 sec', cooldown: '4 min 05 sec', effectDescription: 'Identifies corrupted data nodes/software bugs.' },
      { level: 4, duration: '24 sec', cooldown: '3 min 40 sec', effectDescription: 'Visualizes logic gates to bypass security locks.' },
      { level: 5, duration: '26 sec', cooldown: '3 min 20 sec', effectDescription: 'Predicts system crashes before they happen.' },
      { level: 6, duration: '28 sec', cooldown: '3 min', effectDescription: 'Can trace the physical location of a remote signal source.' },
      { level: 7, duration: '30 sec', cooldown: '2 min 40 sec', effectDescription: 'Highlights trap triggers in electronic systems.' },
      { level: 8, duration: '32 sec', cooldown: '2 min 20 sec', effectDescription: 'Can diagnose problems in cybernetics/implants.' },
      { level: 9, duration: '35 sec', cooldown: '2 min', effectDescription: 'Reroute Logic: Automatically suggests workarounds for broken paths.' },
      { level: 10, duration: '45 sec', cooldown: '1 min 45 sec', effectDescription: 'System Omniscience: Instantly identifies the "Kill Switch" or critical flaw in any electronic or mechanical system.' },
    ],
  },
  'impact-stress-resonance-scan': {
    id: 94,
    slug: 'impact-stress-resonance-scan',
    name: 'Impact Stress Resonance Scan',
    description: 'Vibration analysis tool that identifies structural resonance frequencies to maximize breaching efficiency with kinetic force.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '16 sec', cooldown: '5 min', effectDescription: 'Highlights resonance points; Sledgehammer/Melee breach damage +20%.' },
      { level: 2, duration: '18 sec', cooldown: '4 min 30 sec', effectDescription: 'One-hit breach chance on wooden doors.' },
      { level: 3, duration: '20 sec', cooldown: '4 min 05 sec', effectDescription: 'Breach Damage +35%.' },
      { level: 4, duration: '22 sec', cooldown: '3 min 40 sec', effectDescription: 'Detects hollow spaces behind walls.' },
      { level: 5, duration: '24 sec', cooldown: '3 min 20 sec', effectDescription: 'Resonance strike creates a hole without collapsing the whole wall.' },
      { level: 6, duration: '26 sec', cooldown: '3 min', effectDescription: 'Breach Damage +50%; can damage vehicle armor.' },
      { level: 7, duration: '28 sec', cooldown: '2 min 40 sec', effectDescription: 'Seismic Ping: Striking the wall reveals enemies on the other side.' },
      { level: 8, duration: '30 sec', cooldown: '2 min 20 sec', effectDescription: 'Shatter: Hitting the sweet spot destroys locks/hinges instantly.' },
      { level: 9, duration: '35 sec', cooldown: '2 min', effectDescription: 'Can trigger structural collapse on weakened buildings.' },
      { level: 10, duration: '40 sec', cooldown: '1 min 45 sec', effectDescription: 'Skeleton Key: A single precise kinetic impact opens any physical barrier, door, or hatch regardless of durability.' },
    ],
  },
};
