// ============================================================
// STEALTH & SIGNATURE MANAGEMENT ABILITIES
// Cloaking, noise suppression, thermal/optic concealment, infiltration
// ============================================================

import { ExportedAbility } from './types';

export const STEALTH_SIGNATURE_ABILITIES: Record<string, ExportedAbility> = {
  'concealment-optimization-protocol': {
    id: 201,
    slug: 'concealment-optimization-protocol',
    name: 'Concealment Optimization Protocol',
    description: 'Adaptive camouflage system that analyzes environment and optimizes user visibility reduction.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '20 sec', cooldown: '90 sec', effectDescription: 'Reduce visual signature by 15% when stationary.' },
      { level: 2, duration: '25 sec', cooldown: '85 sec', effectDescription: 'Visual signature -20%; works while moving slowly.' },
      { level: 3, duration: '30 sec', cooldown: '80 sec', effectDescription: 'Visual signature -25%; adapts to lighting changes.' },
      { level: 4, duration: '35 sec', cooldown: '75 sec', effectDescription: 'Visual signature -30%; works while crouching at any speed.' },
      { level: 5, duration: '40 sec', cooldown: '70 sec', effectDescription: 'Visual signature -40%; partial thermal masking.' },
      { level: 6, duration: '45 sec', cooldown: '65 sec', effectDescription: 'Visual signature -50%; full thermal masking while still.' },
      { level: 7, duration: '50 sec', cooldown: '60 sec', effectDescription: 'Visual signature -60%; works while moving normally.' },
      { level: 8, duration: '55 sec', cooldown: '55 sec', effectDescription: 'Visual signature -70%; defeats basic optic sensors.' },
      { level: 9, duration: '60 sec', cooldown: '50 sec', effectDescription: 'Visual signature -80%; works during light combat.' },
      { level: 10, duration: '90 sec', cooldown: '40 sec', effectDescription: 'Adaptive Invisibility: Near-perfect concealment; defeats all non-quantum sensors.' },
    ],
  },
  'ghost-protocol': {
    id: 202,
    slug: 'ghost-protocol',
    name: 'Ghost Protocol',
    description: 'Full-spectrum signature suppression that minimizes all detectable emissions.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '15 sec', cooldown: '120 sec', effectDescription: 'Suppress all emissions by 20%; footsteps muffled.' },
      { level: 2, duration: '18 sec', cooldown: '110 sec', effectDescription: 'Emissions -30%; breathing silenced.' },
      { level: 3, duration: '21 sec', cooldown: '100 sec', effectDescription: 'Emissions -40%; heartbeat undetectable by sensors.' },
      { level: 4, duration: '24 sec', cooldown: '90 sec', effectDescription: 'Emissions -50%; thermal signature minimized.' },
      { level: 5, duration: '27 sec', cooldown: '80 sec', effectDescription: 'Emissions -60%; EM emissions nullified.' },
      { level: 6, duration: '30 sec', cooldown: '70 sec', effectDescription: 'Emissions -70%; motion sensors cannot detect.' },
      { level: 7, duration: '35 sec', cooldown: '65 sec', effectDescription: 'Emissions -80%; scent masked.' },
      { level: 8, duration: '40 sec', cooldown: '60 sec', effectDescription: 'Emissions -90%; AI targeting loses track.' },
      { level: 9, duration: '45 sec', cooldown: '55 sec', effectDescription: 'Emissions -95%; only direct visual contact works.' },
      { level: 10, duration: '60 sec', cooldown: '45 sec', effectDescription: 'True Ghost: 100% emission suppression; effectively invisible to all technology.' },
    ],
  },
  'silent-zeroing-routine': {
    id: 203,
    slug: 'silent-zeroing-routine',
    name: 'Silent Zeroing Routine',
    description: 'Neural-mechanical synchronization that enables completely silent weapon operation.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '30 sec', cooldown: '60 sec', effectDescription: 'Reduce weapon noise by 30%.' },
      { level: 2, duration: '35 sec', cooldown: '55 sec', effectDescription: 'Weapon noise -40%; reload sounds muffled.' },
      { level: 3, duration: '40 sec', cooldown: '50 sec', effectDescription: 'Weapon noise -50%; casing ejection silenced.' },
      { level: 4, duration: '45 sec', cooldown: '45 sec', effectDescription: 'Weapon noise -60%; works with most suppressors.' },
      { level: 5, duration: '50 sec', cooldown: '40 sec', effectDescription: 'Weapon noise -70%; muzzle flash reduced 50%.' },
      { level: 6, duration: '55 sec', cooldown: '35 sec', effectDescription: 'Weapon noise -80%; subsonic rounds auto-optimized.' },
      { level: 7, duration: '60 sec', cooldown: '30 sec', effectDescription: 'Weapon noise -90%; muzzle flash eliminated.' },
      { level: 8, duration: '70 sec', cooldown: '28 sec', effectDescription: 'Weapon noise -95%; impact sounds dampened.' },
      { level: 9, duration: '80 sec', cooldown: '25 sec', effectDescription: 'Weapon nearly silent; victims don\'t hear own death.' },
      { level: 10, duration: '120 sec', cooldown: '20 sec', effectDescription: 'Perfect Silence: Zero weapon noise; can fire full-auto undetected.' },
    ],
  },
  'shadowline-approach-protocol': {
    id: 204,
    slug: 'shadowline-approach-protocol',
    name: 'Shadowline Approach Protocol',
    description: 'Tactical infiltration system that maps shadow coverage for optimal stealth approach.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '45 sec', cooldown: '90 sec', effectDescription: 'Highlights shadow paths on HUD; +10% stealth in shadows.' },
      { level: 2, duration: '50 sec', cooldown: '85 sec', effectDescription: 'Shows patrol blind spots; +15% stealth in shadows.' },
      { level: 3, duration: '55 sec', cooldown: '80 sec', effectDescription: 'Dynamic shadow tracking; +20% stealth in shadows.' },
      { level: 4, duration: '60 sec', cooldown: '75 sec', effectDescription: 'Predicts light source changes; +25% stealth.' },
      { level: 5, duration: '70 sec', cooldown: '70 sec', effectDescription: 'Maps security camera coverage; +30% stealth.' },
      { level: 6, duration: '80 sec', cooldown: '65 sec', effectDescription: 'Shows optimal approach timing; +40% stealth.' },
      { level: 7, duration: '90 sec', cooldown: '60 sec', effectDescription: 'Includes vent/crawlspace routes; +50% stealth.' },
      { level: 8, duration: '100 sec', cooldown: '55 sec', effectDescription: 'Can share shadowline with squad; +60% stealth.' },
      { level: 9, duration: '120 sec', cooldown: '50 sec', effectDescription: 'Creates synthetic shadows using light manipulation.' },
      { level: 10, duration: '180 sec', cooldown: '40 sec', effectDescription: 'Master Infiltrator: Perfect path; +100% stealth; can pass through laser grids.' },
    ],
  },
  'thermal-cut-path-planner': {
    id: 205,
    slug: 'thermal-cut-path-planner',
    name: 'Thermal-Cut Path Planner',
    description: 'Routes navigation to avoid thermal detection systems and hot-spots.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '30 sec', cooldown: '75 sec', effectDescription: 'Highlights thermal-safe paths; body heat -10%.' },
      { level: 2, duration: '35 sec', cooldown: '70 sec', effectDescription: 'Shows thermal sensor locations; heat -15%.' },
      { level: 3, duration: '40 sec', cooldown: '65 sec', effectDescription: 'Dynamic thermal mapping; heat -20%.' },
      { level: 4, duration: '45 sec', cooldown: '60 sec', effectDescription: 'Identifies cold spots for hiding; heat -25%.' },
      { level: 5, duration: '50 sec', cooldown: '55 sec', effectDescription: 'Predicts thermal sweep patterns; heat -30%.' },
      { level: 6, duration: '60 sec', cooldown: '50 sec', effectDescription: 'Can use environment to mask heat; -40%.' },
      { level: 7, duration: '70 sec', cooldown: '45 sec', effectDescription: 'Active heat redistribution; -50%.' },
      { level: 8, duration: '80 sec', cooldown: '40 sec', effectDescription: 'Near-ambient body temperature; -70%.' },
      { level: 9, duration: '90 sec', cooldown: '35 sec', effectDescription: 'Can briefly achieve thermal invisibility.' },
      { level: 10, duration: '120 sec', cooldown: '30 sec', effectDescription: 'Thermal Ghost: Perfect thermal invisibility; can walk past IR sensors undetected.' },
    ],
  },
  'optic-stabilization-matrix': {
    id: 206,
    slug: 'optic-stabilization-matrix',
    name: 'Optic Stabilization Matrix',
    description: 'Visual dampening field that reduces light reflection and glare from equipment.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '40 sec', cooldown: '60 sec', effectDescription: 'Reduce equipment glare by 30%.' },
      { level: 2, duration: '45 sec', cooldown: '55 sec', effectDescription: 'Glare -40%; scope flash eliminated.' },
      { level: 3, duration: '50 sec', cooldown: '50 sec', effectDescription: 'Glare -50%; metal surfaces dulled.' },
      { level: 4, duration: '55 sec', cooldown: '45 sec', effectDescription: 'Glare -60%; glass surfaces non-reflective.' },
      { level: 5, duration: '60 sec', cooldown: '40 sec', effectDescription: 'Glare -70%; even wet surfaces dampened.' },
      { level: 6, duration: '70 sec', cooldown: '35 sec', effectDescription: 'Glare -80%; active light absorption.' },
      { level: 7, duration: '80 sec', cooldown: '30 sec', effectDescription: 'Glare -90%; laser pointer invisible.' },
      { level: 8, duration: '90 sec', cooldown: '27 sec', effectDescription: 'Near-zero reflectivity on all surfaces.' },
      { level: 9, duration: '100 sec', cooldown: '24 sec', effectDescription: 'Eyes themselves non-reflective.' },
      { level: 10, duration: '120 sec', cooldown: '20 sec', effectDescription: 'Light Void: Absorb all light; appear as shadow even under spotlight.' },
    ],
  },
  'ballistic-horizon-protocol': {
    id: 207,
    slug: 'ballistic-horizon-protocol',
    name: 'Ballistic Horizon Protocol',
    description: 'Predictive stealth-sniper system that calculates shot timing to avoid detection.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '20 sec', cooldown: '90 sec', effectDescription: 'Shows safe firing windows; 1 undetected shot.' },
      { level: 2, duration: '25 sec', cooldown: '85 sec', effectDescription: 'Calculates bullet trace invisibility; 2 shots.' },
      { level: 3, duration: '30 sec', cooldown: '80 sec', effectDescription: 'Predicts observer attention; 3 shots.' },
      { level: 4, duration: '35 sec', cooldown: '75 sec', effectDescription: 'Adds ambient noise masking; 4 shots.' },
      { level: 5, duration: '40 sec', cooldown: '70 sec', effectDescription: 'Calculates muzzle flash concealment; 5 shots.' },
      { level: 6, duration: '50 sec', cooldown: '65 sec', effectDescription: 'Synchronized with environmental sounds; 6 shots.' },
      { level: 7, duration: '60 sec', cooldown: '60 sec', effectDescription: 'Full trace path calculation; 8 shots.' },
      { level: 8, duration: '70 sec', cooldown: '55 sec', effectDescription: 'Impact timing matches background noise; 10 shots.' },
      { level: 9, duration: '80 sec', cooldown: '50 sec', effectDescription: 'Near-perfect stealth fire; 12 shots.' },
      { level: 10, duration: '120 sec', cooldown: '40 sec', effectDescription: 'Phantom Sniper: Unlimited undetected shots; enemies cannot trace fire origin.' },
    ],
  },
  'interface-calibration-assist': {
    id: 208,
    slug: 'interface-calibration-assist',
    name: 'Interface Calibration Assist',
    description: 'Precision hacking support that dampens digital signature during system intrusion.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '15 sec', cooldown: '60 sec', effectDescription: 'Reduce hack detection chance by 15%.' },
      { level: 2, duration: '18 sec', cooldown: '55 sec', effectDescription: 'Detection chance -20%; faster hack speed.' },
      { level: 3, duration: '21 sec', cooldown: '50 sec', effectDescription: 'Detection chance -25%; leaves no logs.' },
      { level: 4, duration: '24 sec', cooldown: '45 sec', effectDescription: 'Detection chance -30%; mimics authorized access.' },
      { level: 5, duration: '27 sec', cooldown: '40 sec', effectDescription: 'Detection chance -40%; bypasses basic ICE.' },
      { level: 6, duration: '30 sec', cooldown: '35 sec', effectDescription: 'Detection chance -50%; creates false trails.' },
      { level: 7, duration: '35 sec', cooldown: '30 sec', effectDescription: 'Detection chance -60%; disables countermeasures.' },
      { level: 8, duration: '40 sec', cooldown: '27 sec', effectDescription: 'Detection chance -75%; admin-level spoof.' },
      { level: 9, duration: '45 sec', cooldown: '24 sec', effectDescription: 'Detection chance -90%; hack appears as ghost.' },
      { level: 10, duration: '60 sec', cooldown: '20 sec', effectDescription: 'Digital Ghost: Undetectable intrusion; can rewrite access logs retroactively.' },
    ],
  },
  'heat-bloom-manipulation': {
    id: 209,
    slug: 'heat-bloom-manipulation',
    name: 'Heat Bloom Manipulation',
    description: 'Thermal signature control system that creates decoy heat sources or masks true position.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '12 sec', cooldown: '60 sec', effectDescription: 'Create 1 false heat signature nearby.' },
      { level: 2, duration: '15 sec', cooldown: '55 sec', effectDescription: 'Heat decoy lasts longer; more realistic.' },
      { level: 3, duration: '18 sec', cooldown: '50 sec', effectDescription: 'Create 2 false heat signatures.' },
      { level: 4, duration: '21 sec', cooldown: '45 sec', effectDescription: 'Decoys can move in preset patterns.' },
      { level: 5, duration: '24 sec', cooldown: '40 sec', effectDescription: 'Mask own signature while creating decoy.' },
      { level: 6, duration: '27 sec', cooldown: '35 sec', effectDescription: 'Create 3 false signatures; swap with decoy.' },
      { level: 7, duration: '30 sec', cooldown: '30 sec', effectDescription: 'Decoys replicate weapon signatures.' },
      { level: 8, duration: '35 sec', cooldown: '27 sec', effectDescription: 'Create moving decoy squad.' },
      { level: 9, duration: '40 sec', cooldown: '24 sec', effectDescription: 'Decoys trigger thermal mine systems.' },
      { level: 10, duration: '60 sec', cooldown: '20 sec', effectDescription: 'Thermal Illusion Master: Create entire fake squad; real position untraceable.' },
    ],
  },
};
