// ============================================================
// SUPPORT / MEDICAL / ENGINEERING ABILITIES
// Healing, scanning, emergency response, repairs, squad utility
// ============================================================

import { ExportedAbility } from './types';

export const SUPPORT_MEDICAL_ABILITIES: Record<string, ExportedAbility> = {
  'trauma-triage-overlay': {
    id: 501,
    slug: 'trauma-triage-overlay',
    name: 'Trauma Triage Overlay',
    description: 'Medical HUD that prioritizes casualties and highlights optimal treatment procedures.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '30 sec', cooldown: '60 sec', effectDescription: 'Show ally HP bars; highlight critical wounds.' },
      { level: 2, duration: '35 sec', cooldown: '55 sec', effectDescription: 'Show wound severity; +10% heal speed.' },
      { level: 3, duration: '40 sec', cooldown: '50 sec', effectDescription: 'Auto-prioritize casualties; +15% heal.' },
      { level: 4, duration: '45 sec', cooldown: '45 sec', effectDescription: 'Show treatment steps; +20% heal.' },
      { level: 5, duration: '50 sec', cooldown: '40 sec', effectDescription: 'Predict complications; +25% heal speed.' },
      { level: 6, duration: '55 sec', cooldown: '35 sec', effectDescription: 'Remote diagnosis up to 30m; +30% heal.' },
      { level: 7, duration: '60 sec', cooldown: '30 sec', effectDescription: 'Multi-patient overlay; +40% heal.' },
      { level: 8, duration: '70 sec', cooldown: '27 sec', effectDescription: 'Predict future injuries; +50% heal.' },
      { level: 9, duration: '80 sec', cooldown: '24 sec', effectDescription: 'Full squad medical HUD; +60% heal.' },
      { level: 10, duration: '120 sec', cooldown: '20 sec', effectDescription: 'Combat Surgeon: Perfect diagnosis; +100% heal speed; revive downed allies.' },
    ],
  },
  'micro-surgical-guidance-suite': {
    id: 502,
    slug: 'micro-surgical-guidance-suite',
    name: 'Micro-Surgical Guidance Suite',
    description: 'Precision medical system for field surgery with enhanced accuracy and speed.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '20 sec', cooldown: '90 sec', effectDescription: '+20% surgical precision; faster healing.' },
      { level: 2, duration: '25 sec', cooldown: '85 sec', effectDescription: '+30% precision; stabilize critical.' },
      { level: 3, duration: '30 sec', cooldown: '80 sec', effectDescription: '+40% precision; remove embedded objects.' },
      { level: 4, duration: '35 sec', cooldown: '75 sec', effectDescription: '+50% precision; repair tendons.' },
      { level: 5, duration: '40 sec', cooldown: '70 sec', effectDescription: '+60% precision; repair blood vessels.' },
      { level: 6, duration: '45 sec', cooldown: '65 sec', effectDescription: '+70% precision; nerve repair.' },
      { level: 7, duration: '50 sec', cooldown: '60 sec', effectDescription: '+80% precision; organ repair.' },
      { level: 8, duration: '55 sec', cooldown: '55 sec', effectDescription: '+90% precision; cybernetic repair.' },
      { level: 9, duration: '60 sec', cooldown: '50 sec', effectDescription: '+95% precision; brain surgery.' },
      { level: 10, duration: '90 sec', cooldown: '40 sec', effectDescription: 'Nano-Surgeon: Perfect precision; instant complex surgery; regenerate lost limbs.' },
    ],
  },
  'rapid-repair-guidance': {
    id: 503,
    slug: 'rapid-repair-guidance',
    name: 'Rapid Repair Guidance',
    description: 'Engineering overlay that guides equipment and vehicle repairs with optimal efficiency.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '30 sec', cooldown: '60 sec', effectDescription: 'Highlight damaged components; +15% repair speed.' },
      { level: 2, duration: '35 sec', cooldown: '55 sec', effectDescription: 'Show repair sequence; +20% speed.' },
      { level: 3, duration: '40 sec', cooldown: '50 sec', effectDescription: 'Auto-diagnose faults; +25% speed.' },
      { level: 4, duration: '45 sec', cooldown: '45 sec', effectDescription: 'Highlight shortcuts; +30% speed.' },
      { level: 5, duration: '50 sec', cooldown: '40 sec', effectDescription: 'Predict failures; +40% speed.' },
      { level: 6, duration: '55 sec', cooldown: '35 sec', effectDescription: 'Remote repair assist; +50% speed.' },
      { level: 7, duration: '60 sec', cooldown: '30 sec', effectDescription: 'Multi-system repair; +60% speed.' },
      { level: 8, duration: '70 sec', cooldown: '27 sec', effectDescription: 'Field modifications; +70% speed.' },
      { level: 9, duration: '80 sec', cooldown: '24 sec', effectDescription: 'Improvised repairs; +80% speed.' },
      { level: 10, duration: '120 sec', cooldown: '20 sec', effectDescription: 'Master Engineer: Instant repair; improve equipment beyond original specs.' },
    ],
  },
  'rapid-fortification-overlay': {
    id: 504,
    slug: 'rapid-fortification-overlay',
    name: 'Rapid Fortification Overlay',
    description: 'Tactical construction guide for quickly establishing defensive positions.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '45 sec', cooldown: '90 sec', effectDescription: 'Show optimal cover positions; +10% build speed.' },
      { level: 2, duration: '50 sec', cooldown: '85 sec', effectDescription: 'Highlight materials; +15% build speed.' },
      { level: 3, duration: '55 sec', cooldown: '80 sec', effectDescription: 'Auto-calculate firing lanes; +20% speed.' },
      { level: 4, duration: '60 sec', cooldown: '75 sec', effectDescription: 'Structural optimization; +25% speed.' },
      { level: 5, duration: '70 sec', cooldown: '70 sec', effectDescription: 'Trap placement guide; +30% speed.' },
      { level: 6, duration: '80 sec', cooldown: '65 sec', effectDescription: 'Multi-level fortification; +40% speed.' },
      { level: 7, duration: '90 sec', cooldown: '60 sec', effectDescription: 'Squad coordination build; +50% speed.' },
      { level: 8, duration: '100 sec', cooldown: '55 sec', effectDescription: 'Improvised materials; +60% speed.' },
      { level: 9, duration: '120 sec', cooldown: '50 sec', effectDescription: 'Pre-fab deployment; +75% speed.' },
      { level: 10, duration: '180 sec', cooldown: '40 sec', effectDescription: 'Instant Fortress: Deploy full fortification in seconds; maximum protection.' },
    ],
  },
  'internal-damage-scanner': {
    id: 505,
    slug: 'internal-damage-scanner',
    name: 'Internal Damage Scanner',
    description: 'Deep-tissue scanning that reveals hidden injuries and internal bleeding.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '15 sec', cooldown: '45 sec', effectDescription: 'Detect internal bleeding.' },
      { level: 2, duration: '18 sec', cooldown: '42 sec', effectDescription: 'Detect organ damage.' },
      { level: 3, duration: '21 sec', cooldown: '39 sec', effectDescription: 'Detect bone fractures.' },
      { level: 4, duration: '24 sec', cooldown: '36 sec', effectDescription: 'Detect nerve damage.' },
      { level: 5, duration: '27 sec', cooldown: '33 sec', effectDescription: 'Detect foreign objects.' },
      { level: 6, duration: '30 sec', cooldown: '30 sec', effectDescription: 'Detect toxins/poisons.' },
      { level: 7, duration: '35 sec', cooldown: '27 sec', effectDescription: 'Detect infections.' },
      { level: 8, duration: '40 sec', cooldown: '24 sec', effectDescription: 'Detect cyber-tampering.' },
      { level: 9, duration: '45 sec', cooldown: '21 sec', effectDescription: 'Predict complications.' },
      { level: 10, duration: '60 sec', cooldown: '15 sec', effectDescription: 'Complete Scan: Instant full-body analysis; nothing hidden.' },
    ],
  },
  'organ-stabilization-field': {
    id: 506,
    slug: 'organ-stabilization-field',
    name: 'Organ Stabilization Field',
    description: 'Emergency medical field that prevents organ failure in critical patients.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '20 sec', cooldown: '120 sec', effectDescription: 'Stabilize one organ; prevent failure.' },
      { level: 2, duration: '25 sec', cooldown: '110 sec', effectDescription: 'Stabilize two organs.' },
      { level: 3, duration: '30 sec', cooldown: '100 sec', effectDescription: 'Stabilize all organs; slow bleed.' },
      { level: 4, duration: '35 sec', cooldown: '90 sec', effectDescription: 'Prevent cardiac arrest.' },
      { level: 5, duration: '40 sec', cooldown: '80 sec', effectDescription: 'Stabilize + minor healing.' },
      { level: 6, duration: '45 sec', cooldown: '70 sec', effectDescription: 'Field extends to nearby ally.' },
      { level: 7, duration: '50 sec', cooldown: '60 sec', effectDescription: 'Regenerate damaged tissue.' },
      { level: 8, duration: '55 sec', cooldown: '55 sec', effectDescription: 'Restart failed organs.' },
      { level: 9, duration: '60 sec', cooldown: '50 sec', effectDescription: 'Field stabilizes entire squad.' },
      { level: 10, duration: '90 sec', cooldown: '40 sec', effectDescription: 'Life Support: Complete organ stabilization; target cannot die.' },
    ],
  },
  'emergency-auto-graft-sequencer': {
    id: 507,
    slug: 'emergency-auto-graft-sequencer',
    name: 'Emergency Auto-Graft Sequencer',
    description: 'Automated tissue grafting system for rapid wound closure and repair.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: 'Instant', cooldown: '90 sec', effectDescription: 'Auto-close minor wounds; heal 10%.' },
      { level: 2, duration: 'Instant', cooldown: '85 sec', effectDescription: 'Close moderate wounds; heal 15%.' },
      { level: 3, duration: 'Instant', cooldown: '80 sec', effectDescription: 'Close major wounds; heal 20%.' },
      { level: 4, duration: 'Instant', cooldown: '75 sec', effectDescription: 'Synthetic skin graft; heal 25%.' },
      { level: 5, duration: 'Instant', cooldown: '70 sec', effectDescription: 'Muscle repair; heal 30%.' },
      { level: 6, duration: 'Instant', cooldown: '65 sec', effectDescription: 'Bone fusion; heal 40%.' },
      { level: 7, duration: 'Instant', cooldown: '60 sec', effectDescription: 'Nerve reconnection; heal 50%.' },
      { level: 8, duration: 'Instant', cooldown: '55 sec', effectDescription: 'Organ patch; heal 60%.' },
      { level: 9, duration: 'Instant', cooldown: '50 sec', effectDescription: 'Full tissue regeneration; heal 75%.' },
      { level: 10, duration: 'Instant', cooldown: '40 sec', effectDescription: 'Perfect Restoration: Instant full heal; remove all wounds.' },
    ],
  },
  'rapid-stabilization-protocol': {
    id: 508,
    slug: 'rapid-stabilization-protocol',
    name: 'Rapid Stabilization Protocol',
    description: 'Emergency medical procedure that quickly stabilizes a downed ally.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '5 sec channel', cooldown: '60 sec', effectDescription: 'Stabilize downed ally; revive at 10% HP.' },
      { level: 2, duration: '4.5 sec channel', cooldown: '55 sec', effectDescription: 'Revive at 15% HP.' },
      { level: 3, duration: '4 sec channel', cooldown: '50 sec', effectDescription: 'Revive at 20% HP; remove bleed.' },
      { level: 4, duration: '3.5 sec channel', cooldown: '45 sec', effectDescription: 'Revive at 25% HP.' },
      { level: 5, duration: '3 sec channel', cooldown: '40 sec', effectDescription: 'Revive at 30% HP; immunity 3 sec.' },
      { level: 6, duration: '2.5 sec channel', cooldown: '35 sec', effectDescription: 'Revive at 40% HP.' },
      { level: 7, duration: '2 sec channel', cooldown: '30 sec', effectDescription: 'Revive at 50% HP; remove debuffs.' },
      { level: 8, duration: '1.5 sec channel', cooldown: '27 sec', effectDescription: 'Revive at 60% HP.' },
      { level: 9, duration: '1 sec channel', cooldown: '24 sec', effectDescription: 'Revive at 75% HP; immunity 5 sec.' },
      { level: 10, duration: 'Instant', cooldown: '20 sec', effectDescription: 'Instant Revive: Ally returns at 100% HP; 10 sec immunity.' },
    ],
  },
  'squad-sync-overdrive': {
    id: 509,
    slug: 'squad-sync-overdrive',
    name: 'Squad Sync Overdrive',
    description: 'TL9 neural link that synchronizes squad movements and reactions for perfect coordination.',
    maxLevel: 10,
    tiers: [
      { level: 1, duration: '15 sec', cooldown: '120 sec', effectDescription: 'Squad shares basic positioning data; +5% coordination.' },
      { level: 2, duration: '18 sec', cooldown: '110 sec', effectDescription: 'Share threat markers; +10% coordination.' },
      { level: 3, duration: '21 sec', cooldown: '100 sec', effectDescription: 'Share targeting data; +15% coordination.' },
      { level: 4, duration: '24 sec', cooldown: '90 sec', effectDescription: 'Synchronized reloads; +20% coordination.' },
      { level: 5, duration: '27 sec', cooldown: '80 sec', effectDescription: 'Movement prediction; +30% coordination.' },
      { level: 6, duration: '30 sec', cooldown: '70 sec', effectDescription: 'Combined fire bonuses; +40% coordination.' },
      { level: 7, duration: '35 sec', cooldown: '60 sec', effectDescription: 'Shared reflexes; +50% coordination.' },
      { level: 8, duration: '40 sec', cooldown: '55 sec', effectDescription: 'Instant communication; +60% coordination.' },
      { level: 9, duration: '45 sec', cooldown: '50 sec', effectDescription: 'Shared abilities; +75% coordination.' },
      { level: 10, duration: '60 sec', cooldown: '40 sec', effectDescription: 'Hive Mind: Perfect synchronization; squad acts as one entity.' },
    ],
  },
};
